# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bienvenida.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ventanas.imagenes import imagenes


class Ui_UserSelection(object):
    def setupUi(self, UserSelection):
        UserSelection.setObjectName("UserSelection")
        UserSelection.resize(450, 550)
        UserSelection.setStyleSheet("")
        UserSelection.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        UserSelection.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(UserSelection)
        self.widget.setGeometry(QtCore.QRect(30, 30, 370, 480))
        self.widget.setStyleSheet(
            "QPushButton#boton_vendedor,#boton_usuario_autorizado{    \n"
            "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
            "    color:rgba(255, 255, 255, 210);\n"
            "    border-radius:5px;\n"
            "}\n"
            "QPushButton#boton_vendedor:hover,#boton_usuario_autorizado:hover{    \n"
            "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
            "}\n"
            "QPushButton#boton_vendedor:pressed,#boton_usuario_autorizado:pressed{    \n"
            "    padding-left:5px;\n"
            "    padding-top:5px;\n"
            "    background-color:rgba(105, 118, 132, 200);\n"
            "}\n"
            "\n"
            "QPushButton#pushButton_2, #pushButton_3, #pushButton_4, #pushButton_5{    \n"
            "    background-color: rgba(0, 0, 0, 0);\n"
            "    color:rgba(85, 98, 112, 255);\n"
            "}\n"
            "QPushButton#pushButton_2:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_5:hover{    \n"
            "    color:rgba(155, 168, 182, 220);\n"
            "}\n"
            "QPushButton#pushButton_2:pressed, #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_5:pressed{    \n"
            "    padding-left:5px;\n"
            "    padding-top:5px;\n"
            "    color:rgba(115, 128, 142, 255);\n"
            "}"
        )
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 30, 300, 420))
        self.label.setStyleSheet(
            "border-image: url(:/bienvenida/bienvenida_background.png);\n"
            "border-radius:20px;"
        )
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 300, 420))
        self.label_2.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 9), stop:0.375 rgba(0, 0, 0, 50), stop:0.835227 rgba(0, 0, 0, 75));\n"
            "border-radius:20px;"
        )
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(40, 60, 280, 390))
        self.label_3.setStyleSheet(
            "background-color:rgba(0, 0, 0, 100);\n" "border-radius:15px;"
        )
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(70, 90, 231, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgba(255, 255, 255, 210);")
        self.label_4.setObjectName("label_4")
        self.boton_usuario_autorizado = QtWidgets.QPushButton(self.widget)
        self.boton_usuario_autorizado.setGeometry(QtCore.QRect(80, 290, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boton_usuario_autorizado.setFont(font)
        self.boton_usuario_autorizado.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_usuario_autorizado.setObjectName("boton_usuario_autorizado")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(120, 400, 121, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.boton_vendedor = QtWidgets.QPushButton(self.widget)
        self.boton_vendedor.setGeometry(QtCore.QRect(80, 190, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boton_vendedor.setFont(font)
        self.boton_vendedor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_vendedor.setObjectName("boton_vendedor")

        self.retranslateUi(UserSelection)
        QtCore.QMetaObject.connectSlotsByName(UserSelection)

    def retranslateUi(self, UserSelection):
        _translate = QtCore.QCoreApplication.translate
        UserSelection.setWindowTitle(_translate("UserSelection", "Form"))
        self.label_4.setText(_translate("UserSelection", "Como desea ingresar?"))
        self.boton_usuario_autorizado.setText(
            _translate("UserSelection", "Usuario Autorizado")
        )
        self.pushButton_3.setText(_translate("UserSelection", "M"))
        self.pushButton_4.setText(_translate("UserSelection", "M"))
        self.boton_vendedor.setText(_translate("UserSelection", "Vendedor"))
