# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'elegir_tipo_compra.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from ventanas.imagenes import imagenes


class Ui_ElegirTipoCompra(object):
    def setupUi(self, ElegirTipoCompra):
        ElegirTipoCompra.setObjectName("ElegirTipoCompra")
        ElegirTipoCompra.resize(425, 522)
        ElegirTipoCompra.setStyleSheet("")
        ElegirTipoCompra.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        ElegirTipoCompra.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(ElegirTipoCompra)
        self.widget.setGeometry(QtCore.QRect(30, 20, 370, 480))
        self.widget.setStyleSheet(
            "QPushButton#boton_nuevo_producto,#boton_producto_en_stock,#boton_volver{    \n"
            "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
            "    color:rgba(255, 255, 255, 210);\n"
            "    border-radius:5px;\n"
            "}\n"
            "QPushButton#boton_nuevo_producto:hover,#boton_producto_en_stock:hover,#boton_volver:hover{    \n"
            "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
            "}\n"
            "QPushButton#boton_nuevo_producto:pressed,#boton_producto_en_stock:pressed,#boton_volver:pressed{    \n"
            "    padding-left:5px;\n"
            "    padding-top:5px;\n"
            "    background-color:rgba(105, 118, 132, 200);\n"
            "}\n"
            "\n"
            "QPushButton#pushButton_2, #pushButton_3, #pushButton_4, #pushButton_5{    \n"
            "    background-color: rgba(0, 0, 0, 0);\n"
            "    color:rgba(85, 98, 112, 255);\n"
            "}\n"
            "QPushButton#pushButton_2:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_5:hover{    \n"
            "    color:rgba(155, 168, 182, 220);\n"
            "}\n"
            "QPushButton#pushButton_2:pressed, #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_5:pressed{    \n"
            "    padding-left:5px;\n"
            "    padding-top:5px;\n"
            "    color:rgba(115, 128, 142, 255);\n"
            "};"
        )
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 30, 300, 420))
        self.label.setStyleSheet(
            "background-image: url(:/elegir_tipo_compra/elegir_compra_background.png);\n"
            "border-radius:20px;"
        )
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 300, 420))
        self.label_2.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 9), stop:0.375 rgba(0, 0, 0, 50), stop:0.835227 rgba(0, 0, 0, 75));\n"
            "background-image: url(:/tipo_usuario/FACULTAD 4/TRABAJO SANDRO/imagenes/usuario_autorizado.png);\n"
            "border-radius:20px;"
        )
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(40, 60, 280, 390))
        self.label_3.setStyleSheet(
            "background-color:rgba(0, 0, 0, 50);\n" "border-radius:15px;"
        )
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(70, 90, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(
            "color:rgba(255, 255, 255, 210);\n" "background-color:none;"
        )
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.boton_nuevo_producto = QtWidgets.QPushButton(self.widget)
        self.boton_nuevo_producto.setGeometry(QtCore.QRect(80, 290, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boton_nuevo_producto.setFont(font)
        self.boton_nuevo_producto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_nuevo_producto.setObjectName("boton_nuevo_producto")
        self.boton_producto_en_stock = QtWidgets.QPushButton(self.widget)
        self.boton_producto_en_stock.setGeometry(QtCore.QRect(80, 190, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boton_producto_en_stock.setFont(font)
        self.boton_producto_en_stock.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_producto_en_stock.setObjectName("boton_producto_en_stock")
        self.boton_volver = QtWidgets.QPushButton(self.widget)
        self.boton_volver.setGeometry(QtCore.QRect(140, 400, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boton_volver.setFont(font)
        self.boton_volver.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_volver.setObjectName("boton_volver")

        self.retranslateUi(ElegirTipoCompra)
        QtCore.QMetaObject.connectSlotsByName(ElegirTipoCompra)

    def retranslateUi(self, ElegirTipoCompra):
        _translate = QtCore.QCoreApplication.translate
        ElegirTipoCompra.setWindowTitle(_translate("ElegirTipoCompra", "Form"))
        self.label_4.setText(_translate("ElegirTipoCompra", "Que compra se cargara?"))
        self.boton_nuevo_producto.setText(
            _translate("ElegirTipoCompra", "Nuevo Producto")
        )
        self.boton_producto_en_stock.setText(
            _translate("ElegirTipoCompra", "Producto en Stock")
        )
        self.boton_volver.setText(_translate("ElegirTipoCompra", "Volver"))
