# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from ventanas.imagenes import imagenes


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(625, 565)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 30, 550, 500))
        self.widget.setStyleSheet(
            "QPushButton#boton_ingresar,#boton_volver{\n"
            "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
            "    color:rgba(255, 255, 255, 210);\n"
            "    border-radius:5px;\n"
            "}\n"
            "\n"
            "QPushButton#boton_ingresar:hover,#boton_volver:hover{\n"
            "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
            "}\n"
            "\n"
            "QPushButton#boton_ingresar:pressed,#boton_volver:pressed{\n"
            "    padding-left:5px;\n"
            "    padding-top:5px;\n"
            "    background-color:rgba(150, 123, 111, 255);\n"
            "}\n"
            "\n"
            "QPushButton#pushButton_2, #pushButton_3, #pushButton_4, #pushButton_5{\n"
            "    background-color: rgba(0, 0, 0, 0);\n"
            "    color:rgba(85, 98, 112, 255);\n"
            "}\n"
            "\n"
            "QPushButton#pushButton_2:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_5:hover{\n"
            "    color: rgba(131, 96, 53, 255);\n"
            "}\n"
            "\n"
            "QPushButton#pushButton_2:pressed, #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_5:pressed{\n"
            "    padding-left:5px;\n"
            "    padding-top:5px;\n"
            "    color:rgba(91, 88, 53, 255);\n"
            "}\n"
            "\n"
            ""
        )
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(40, 30, 280, 430))
        self.label.setStyleSheet(
            "border-image: url(:/login/login_background.jpg);\n"
            "border-top-left-radius: 50px;"
        )
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(40, 30, 280, 430))
        self.label_2.setStyleSheet(
            "background-color:rgba(0, 0, 0, 80);\n" "border-top-left-radius: 50px;"
        )
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(270, 30, 240, 430))
        self.label_3.setStyleSheet(
            "background-color:rgba(255, 255, 255, 255);\n"
            "border-bottom-right-radius: 50px;"
        )
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(300, 80, 181, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgba(0, 0, 0, 200);")
        self.label_4.setObjectName("label_4")
        self.usuario_ingresado = QtWidgets.QLineEdit(self.widget)
        self.usuario_ingresado.setGeometry(QtCore.QRect(295, 150, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.usuario_ingresado.setFont(font)
        self.usuario_ingresado.setStyleSheet(
            "background-color:rgba(0, 0, 0, 0);\n"
            "border:none;\n"
            "border-bottom:2px solid rgba(46, 82, 101, 200);\n"
            "color:rgba(0, 0, 0, 240);\n"
            "padding-bottom:7px;"
        )
        self.usuario_ingresado.setObjectName("usuario_ingresado")
        self.contrasenia_ingresada = QtWidgets.QLineEdit(self.widget)
        self.contrasenia_ingresada.setGeometry(QtCore.QRect(295, 215, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.contrasenia_ingresada.setFont(font)
        self.contrasenia_ingresada.setStyleSheet(
            "background-color:rgba(0, 0, 0, 0);\n"
            "border:none;\n"
            "border-bottom:2px solid rgba(46, 82, 101, 200);\n"
            "color:rgba(0, 0, 0, 240);\n"
            "padding-bottom:7px;"
        )
        self.contrasenia_ingresada.setEchoMode(QtWidgets.QLineEdit.Password)
        self.contrasenia_ingresada.setObjectName("contrasenia_ingresada")
        self.boton_ingresar = QtWidgets.QPushButton(self.widget)
        self.boton_ingresar.setGeometry(QtCore.QRect(295, 295, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.boton_ingresar.setFont(font)
        self.boton_ingresar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_ingresar.setObjectName("boton_ingresar")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(40, 80, 230, 130))
        self.label_6.setStyleSheet("background-color:rgba(0, 0, 0, 75);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(50, 80, 180, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgba(255, 255, 255, 200);")
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(50, 145, 220, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgba(255, 255, 255, 170);")
        self.label_8.setObjectName("label_8")
        self.boton_volver = QtWidgets.QPushButton(self.widget)
        self.boton_volver.setGeometry(QtCore.QRect(350, 390, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.boton_volver.setFont(font)
        self.boton_volver.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_volver.setObjectName("boton_volver")
        self.campos_no_validos = QtWidgets.QLabel(self.widget)
        self.campos_no_validos.setGeometry(QtCore.QRect(290, 260, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.campos_no_validos.setFont(font)
        self.campos_no_validos.setStyleSheet(
            "background-color:rgba(0, 0, 0, 0);\n"
            "border:none;\n"
            "color:red;\n"
            "padding-bottom:7px;"
        )
        self.campos_no_validos.setText("")
        self.campos_no_validos.setObjectName("campos_no_validos")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Inicio Sesion"))
        self.usuario_ingresado.setPlaceholderText(_translate("Form", "Usuario"))
        self.contrasenia_ingresada.setPlaceholderText(_translate("Form", "Contaseña"))
        self.boton_ingresar.setText(_translate("Form", "Ingresar"))
        self.label_7.setText(_translate("Form", "Miracle Multimarcas"))
        self.label_8.setText(_translate("Form", "Hola,\n" "Bienvenido nuevamente."))
        self.boton_volver.setText(_translate("Form", "Volver"))
