# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modificar_comisiones.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ventanas.imagenes import imagenes


class Ui_ModificarComisiones(object):
    def setupUi(self, ModificarComisiones):
        ModificarComisiones.setObjectName("ModificarComisiones")
        ModificarComisiones.resize(680, 579)
        ModificarComisiones.setMinimumSize(QtCore.QSize(680, 579))
        ModificarComisiones.setMaximumSize(QtCore.QSize(680, 579))
        ModificarComisiones.setStyleSheet("")
        self.widget = QtWidgets.QWidget(ModificarComisiones)
        self.widget.setGeometry(QtCore.QRect(0, 0, 680, 579))
        self.widget.setMinimumSize(QtCore.QSize(680, 579))
        self.widget.setMaximumSize(QtCore.QSize(680, 579))
        self.widget.setStyleSheet(
            "QLabel{\n"
            'font: 57 12pt "Yu Gothic Medium";\n'
            "color: #fff;\n"
            "background: none;\n"
            "}\n"
            "QWidget#widget{\n"
            "    background-image: url(:/ganancias/ganancias-background.png);\n"
            "}\n"
            "QRadioButton{\n"
            "background: none;\n"
            "color: white;\n"
            "}\n"
            "QPushButton{\n"
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(0, 158, 255, 255));\n"
            "color:#fff;\n"
            'font: 57 10pt "Yu Gothic Medium";\n'
            "border-radius: 5px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(196, 196, 196, 255), stop:1 rgba(0, 158, 255, 255));\n"
            "}\n"
            "QPushButton:pressed{\n"
            "padding-top:10px;\n"
            "padding-left:10px;\n"
            "}\n"
            "QLineEdit{\n"
            "background:transparent;\n"
            "border:none;\n"
            "border-bottom: 1px solid #fff;\n"
            "color:#fff;\n"
            "}"
        )
        self.widget.setObjectName("widget")
        self.fondo = QtWidgets.QLabel(self.widget)
        self.fondo.setGeometry(QtCore.QRect(0, 0, 680, 579))
        self.fondo.setMinimumSize(QtCore.QSize(680, 579))
        self.fondo.setMaximumSize(QtCore.QSize(680, 579))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.fondo.setFont(font)
        self.fondo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fondo.setStyleSheet(
            "background-image: url(:/ganancias/ganancias-background.png);"
        )
        self.fondo.setText("")
        self.fondo.setAlignment(QtCore.Qt.AlignCenter)
        self.fondo.setObjectName("fondo")
        self.fondo2 = QtWidgets.QLabel(self.widget)
        self.fondo2.setGeometry(QtCore.QRect(60, 20, 561, 531))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.fondo2.setFont(font)
        self.fondo2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fondo2.setStyleSheet(
            "border-radius: 50px;\n"
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(45, 45, 45, 162));"
        )
        self.fondo2.setText("")
        self.fondo2.setAlignment(QtCore.Qt.AlignCenter)
        self.fondo2.setObjectName("fondo2")
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setGeometry(QtCore.QRect(250, 100, 201, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setStyleSheet(
            'font: 25pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.boton_volver = QtWidgets.QPushButton(self.widget)
        self.boton_volver.setGeometry(QtCore.QRect(10, 30, 91, 31))
        self.boton_volver.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_volver.setStyleSheet("")
        self.boton_volver.setObjectName("boton_volver")
        self.boton_modificar_comision_mercadolibre = QtWidgets.QPushButton(self.widget)
        self.boton_modificar_comision_mercadolibre.setGeometry(
            QtCore.QRect(90, 220, 211, 51)
        )
        self.boton_modificar_comision_mercadolibre.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_modificar_comision_mercadolibre.setStyleSheet("")
        self.boton_modificar_comision_mercadolibre.setObjectName(
            "boton_modificar_comision_mercadolibre"
        )
        self.boton_modificar_comision_posnet = QtWidgets.QPushButton(self.widget)
        self.boton_modificar_comision_posnet.setGeometry(
            QtCore.QRect(390, 220, 201, 51)
        )
        self.boton_modificar_comision_posnet.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_modificar_comision_posnet.setStyleSheet("")
        self.boton_modificar_comision_posnet.setObjectName(
            "boton_modificar_comision_posnet"
        )
        self.widget_modificar_comision = QtWidgets.QWidget(self.widget)
        self.widget_modificar_comision.setGeometry(QtCore.QRect(170, 320, 371, 211))
        self.widget_modificar_comision.setObjectName("widget_modificar_comision")
        self.label_ingrese_porcentaje = QtWidgets.QLabel(self.widget_modificar_comision)
        self.label_ingrese_porcentaje.setGeometry(QtCore.QRect(70, 20, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_ingrese_porcentaje.setFont(font)
        self.label_ingrese_porcentaje.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_ingrese_porcentaje.setStyleSheet("")
        self.label_ingrese_porcentaje.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ingrese_porcentaje.setWordWrap(True)
        self.label_ingrese_porcentaje.setObjectName("label_ingrese_porcentaje")
        self.label_fecha_final = QtWidgets.QLabel(self.widget_modificar_comision)
        self.label_fecha_final.setGeometry(QtCore.QRect(210, 100, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_fecha_final.setFont(font)
        self.label_fecha_final.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_fecha_final.setStyleSheet("font-size:18px;")
        self.label_fecha_final.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fecha_final.setObjectName("label_fecha_final")
        self.input_porcentaje_comision = QtWidgets.QLineEdit(
            self.widget_modificar_comision
        )
        self.input_porcentaje_comision.setGeometry(QtCore.QRect(150, 90, 61, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.input_porcentaje_comision.setFont(font)
        self.input_porcentaje_comision.setStyleSheet("")
        self.input_porcentaje_comision.setAlignment(QtCore.Qt.AlignCenter)
        self.input_porcentaje_comision.setObjectName("input_porcentaje_comision")
        self.boton_modificar_comision = QtWidgets.QPushButton(
            self.widget_modificar_comision
        )
        self.boton_modificar_comision.setGeometry(QtCore.QRect(130, 170, 101, 31))
        self.boton_modificar_comision.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_modificar_comision.setStyleSheet("")
        self.boton_modificar_comision.setObjectName("boton_modificar_comision")
        self.label_porcentaje_no_valido = QtWidgets.QLabel(
            self.widget_modificar_comision
        )
        self.label_porcentaje_no_valido.setGeometry(QtCore.QRect(10, 80, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_porcentaje_no_valido.setFont(font)
        self.label_porcentaje_no_valido.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_porcentaje_no_valido.setStyleSheet("color:#f00;")
        self.label_porcentaje_no_valido.setAlignment(QtCore.Qt.AlignCenter)
        self.label_porcentaje_no_valido.setWordWrap(True)
        self.label_porcentaje_no_valido.setObjectName("label_porcentaje_no_valido")

        self.retranslateUi(ModificarComisiones)
        QtCore.QMetaObject.connectSlotsByName(ModificarComisiones)

    def retranslateUi(self, ModificarComisiones):
        _translate = QtCore.QCoreApplication.translate
        ModificarComisiones.setWindowTitle(_translate("ModificarComisiones", "Form"))
        self.label_16.setText(_translate("ModificarComisiones", "COMISIONES"))
        self.boton_volver.setText(_translate("ModificarComisiones", "Volver"))
        self.boton_modificar_comision_mercadolibre.setText(
            _translate("ModificarComisiones", "Nueva comision de MercadoLibre")
        )
        self.boton_modificar_comision_posnet.setText(
            _translate("ModificarComisiones", "Nueva comision de Posnet")
        )
        self.label_ingrese_porcentaje.setText(
            _translate(
                "ModificarComisiones", "Nuevo porcentaje de comision de MercadoLibre"
            )
        )
        self.label_fecha_final.setText(_translate("ModificarComisiones", "%"))
        self.boton_modificar_comision.setText(
            _translate("ModificarComisiones", "MODIFICAR")
        )
