# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registrar_compra_producto_nuevo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from ventanas.imagenes import imagenes


class Ui_RegistrarCompraProductoNuevo(object):
    def setupUi(self, RegistrarCompraProductoNuevo):
        RegistrarCompraProductoNuevo.setObjectName("RegistrarCompraProductoNuevo")
        RegistrarCompraProductoNuevo.resize(1195, 877)
        RegistrarCompraProductoNuevo.setMinimumSize(QtCore.QSize(1195, 877))
        RegistrarCompraProductoNuevo.setMaximumSize(QtCore.QSize(1195, 877))
        RegistrarCompraProductoNuevo.setStyleSheet("")
        self.widget = QtWidgets.QWidget(RegistrarCompraProductoNuevo)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1195, 877))
        self.widget.setMinimumSize(QtCore.QSize(1195, 877))
        self.widget.setMaximumSize(QtCore.QSize(1195, 877))
        self.widget.setStyleSheet(
            "QPushButton{\n"
            'font: 57 11pt "Yu Gothic Medium";\n'
            "color: #fff;\n"
            "padding:5px;\n"
            "    background-color: qlineargradient(spread:pad, x1:0.421, y1:0.636863, x2:1, y2:0, stop:0 rgba(52, 190, 250, 172), stop:1 rgba(255, 255, 255, 158));\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: qlineargradient(spread:pad, x1:0.421, y1:0.636863, x2:1, y2:0, stop:0 rgba(41, 151, 199, 172), stop:1 rgba(255, 255, 255, 158));\n"
            "}\n"
            "QPushButton:pressed {\n"
            "    padding-top: 10px;\n"
            "    padding-left: 10px;\n"
            "}\n"
            "QLineEdit{\n"
            "padding: 3px;\n"
            "color: #fff; \n"
            'font: 11pt "MS Shell Dlg 2";\n'
            "    background-color: qlineargradient(spread:pad, x1:0.421, y1:0.636863, x2:1, y2:0, stop:0 rgba(52, 190, 250, 172), stop:1 rgba(255, 255, 255, 158));\n"
            "}\n"
            "QLineEdit:hover {\n"
            "    background-color: qlineargradient(spread:pad, x1:0.421, y1:0.636863, x2:1, y2:0, stop:0 rgba(41, 151, 199, 172), stop:1 rgba(255, 255, 255, 158));\n"
            "}\n"
            "QLineEdit:focus {\n"
            "    background-color: qlineargradient(spread:pad, x1:0.421, y1:0.636863, x2:1, y2:0, stop:0 rgba(41, 151, 199, 172), stop:1 rgba(255, 255, 255, 158));\n"
            "color:#fff;\n"
            "}\n"
            "QRadioButton{\n"
            "color:#fff;\n"
            "background-color: none;\n"
            'font: 57 14pt "Yu Gothic Medium";\n'
            "}\n"
            "QTreeView{\n"
            " background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(101, 101, 101, 162));\n"
            "color: #fff;\n"
            "border: 1px solid #fff;\n"
            "}\n"
            "QHeaderView::section {\n"
            "color: #000;\n"
            "border: 1px solid #000;\n"
            "}\n"
            "QTreeView::item {\n"
            "color: #fff;\n"
            "}\n"
            "QWidget#widget{\n"
            "    background-image: url(:/registrar_compras/3376284.jpg);\n"
            "}\n"
            "QLabel{\n"
            "color:#fff;\n"
            "}"
        )
        self.widget.setObjectName("widget")
        self.input_precio_unitario = QtWidgets.QLineEdit(self.widget)
        self.input_precio_unitario.setGeometry(QtCore.QRect(1030, 230, 121, 31))
        self.input_precio_unitario.setStyleSheet("")
        self.input_precio_unitario.setText("")
        self.input_precio_unitario.setFrame(True)
        self.input_precio_unitario.setAlignment(QtCore.Qt.AlignCenter)
        self.input_precio_unitario.setObjectName("input_precio_unitario")
        self.label_tipo_pago_no_elegido_3 = QtWidgets.QLabel(self.widget)
        self.label_tipo_pago_no_elegido_3.setGeometry(QtCore.QRect(1010, 230, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_tipo_pago_no_elegido_3.setFont(font)
        self.label_tipo_pago_no_elegido_3.setStyleSheet("")
        self.label_tipo_pago_no_elegido_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tipo_pago_no_elegido_3.setObjectName("label_tipo_pago_no_elegido_3")
        self.boton_buscar_producto = QtWidgets.QPushButton(self.widget)
        self.boton_buscar_producto.setGeometry(QtCore.QRect(460, 100, 101, 31))
        self.boton_buscar_producto.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_buscar_producto.setStyleSheet("border-radius:10px;")
        self.boton_buscar_producto.setObjectName("boton_buscar_producto")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(660, 200, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.boton_registrar_compra = QtWidgets.QPushButton(self.widget)
        self.boton_registrar_compra.setGeometry(QtCore.QRect(840, 370, 131, 41))
        self.boton_registrar_compra.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_registrar_compra.setStyleSheet("")
        self.boton_registrar_compra.setObjectName("boton_registrar_compra")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(1000, 200, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("")
        self.label_9.setObjectName("label_9")
        self.label_tipo_pago_no_elegido_2 = QtWidgets.QLabel(self.widget)
        self.label_tipo_pago_no_elegido_2.setGeometry(QtCore.QRect(830, 230, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_tipo_pago_no_elegido_2.setFont(font)
        self.label_tipo_pago_no_elegido_2.setStyleSheet("")
        self.label_tipo_pago_no_elegido_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tipo_pago_no_elegido_2.setObjectName("label_tipo_pago_no_elegido_2")
        self.eleccion_posnet = QtWidgets.QRadioButton(self.widget)
        self.eleccion_posnet.setGeometry(QtCore.QRect(860, 320, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.eleccion_posnet.setFont(font)
        self.eleccion_posnet.setStyleSheet("background-color: none;")
        self.eleccion_posnet.setObjectName("eleccion_posnet")
        self.eleccion_efectivo = QtWidgets.QRadioButton(self.widget)
        self.eleccion_efectivo.setGeometry(QtCore.QRect(720, 320, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.eleccion_efectivo.setFont(font)
        self.eleccion_efectivo.setStyleSheet("background-color: none;")
        self.eleccion_efectivo.setObjectName("eleccion_efectivo")
        self.producto_no_encontrado = QtWidgets.QLabel(self.widget)
        self.producto_no_encontrado.setGeometry(QtCore.QRect(160, 130, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.producto_no_encontrado.setFont(font)
        self.producto_no_encontrado.setStyleSheet("color:#f00;")
        self.producto_no_encontrado.setText("")
        self.producto_no_encontrado.setObjectName("producto_no_encontrado")
        self.boton_volver = QtWidgets.QPushButton(self.widget)
        self.boton_volver.setGeometry(QtCore.QRect(1090, 20, 101, 31))
        self.boton_volver.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_volver.setStyleSheet("")
        self.boton_volver.setObjectName("boton_volver")
        self.input_buscar_producto = QtWidgets.QLineEdit(self.widget)
        self.input_buscar_producto.setGeometry(QtCore.QRect(40, 100, 411, 31))
        self.input_buscar_producto.setStyleSheet("")
        self.input_buscar_producto.setText("")
        self.input_buscar_producto.setAlignment(QtCore.Qt.AlignCenter)
        self.input_buscar_producto.setObjectName("input_buscar_producto")
        self.treeview_productos = QtWidgets.QTreeView(self.widget)
        self.treeview_productos.setGeometry(QtCore.QRect(20, 160, 591, 691))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.treeview_productos.setFont(font)
        self.treeview_productos.setStyleSheet("padding: 0px;")
        self.treeview_productos.setAllColumnsShowFocus(False)
        self.treeview_productos.setObjectName("treeview_productos")
        self.eleccion_mercadopago = QtWidgets.QRadioButton(self.widget)
        self.eleccion_mercadopago.setGeometry(QtCore.QRect(980, 320, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.eleccion_mercadopago.setFont(font)
        self.eleccion_mercadopago.setStyleSheet("background-color: none;")
        self.eleccion_mercadopago.setObjectName("eleccion_mercadopago")
        self.treeview_compras = QtWidgets.QTreeView(self.widget)
        self.treeview_compras.setGeometry(QtCore.QRect(620, 430, 561, 421))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.treeview_compras.setFont(font)
        self.treeview_compras.setStyleSheet("padding: 0px;")
        self.treeview_compras.setAllColumnsShowFocus(False)
        self.treeview_compras.setObjectName("treeview_compras")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(670, 140, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.input_costo_unitario = QtWidgets.QLineEdit(self.widget)
        self.input_costo_unitario.setGeometry(QtCore.QRect(850, 230, 121, 31))
        self.input_costo_unitario.setStyleSheet("")
        self.input_costo_unitario.setText("")
        self.input_costo_unitario.setFrame(True)
        self.input_costo_unitario.setAlignment(QtCore.Qt.AlignCenter)
        self.input_costo_unitario.setObjectName("input_costo_unitario")
        self.input_nombre_producto = QtWidgets.QLineEdit(self.widget)
        self.input_nombre_producto.setGeometry(QtCore.QRect(810, 140, 331, 31))
        self.input_nombre_producto.setStyleSheet("")
        self.input_nombre_producto.setText("")
        self.input_nombre_producto.setFrame(True)
        self.input_nombre_producto.setAlignment(QtCore.Qt.AlignCenter)
        self.input_nombre_producto.setObjectName("input_nombre_producto")
        self.input_cantidad_comprada = QtWidgets.QLineEdit(self.widget)
        self.input_cantidad_comprada.setGeometry(QtCore.QRect(700, 230, 71, 31))
        self.input_cantidad_comprada.setStyleSheet("")
        self.input_cantidad_comprada.setText("")
        self.input_cantidad_comprada.setFrame(True)
        self.input_cantidad_comprada.setAlignment(QtCore.Qt.AlignCenter)
        self.input_cantidad_comprada.setObjectName("input_cantidad_comprada")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(60, 40, 491, 41))
        self.label.setStyleSheet(
            'font: 36pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(850, 200, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(780, 290, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.label_error_al_registrar = QtWidgets.QLabel(self.widget)
        self.label_error_al_registrar.setGeometry(QtCore.QRect(690, 380, 151, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_error_al_registrar.setFont(font)
        self.label_error_al_registrar.setStyleSheet("color:#f00;")
        self.label_error_al_registrar.setText("")
        self.label_error_al_registrar.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error_al_registrar.setObjectName("label_error_al_registrar")

        self.retranslateUi(RegistrarCompraProductoNuevo)
        QtCore.QMetaObject.connectSlotsByName(RegistrarCompraProductoNuevo)

    def retranslateUi(self, RegistrarCompraProductoNuevo):
        _translate = QtCore.QCoreApplication.translate
        RegistrarCompraProductoNuevo.setWindowTitle(
            _translate("RegistrarCompraProductoNuevo", "Form")
        )
        self.label_tipo_pago_no_elegido_3.setText(
            _translate("RegistrarCompraProductoNuevo", "$")
        )
        self.boton_buscar_producto.setText(
            _translate("RegistrarCompraProductoNuevo", "Buscar")
        )
        self.label_7.setText(
            _translate("RegistrarCompraProductoNuevo", "Cantidad comprada:")
        )
        self.boton_registrar_compra.setText(
            _translate("RegistrarCompraProductoNuevo", "REGISTRAR")
        )
        self.label_9.setText(
            _translate("RegistrarCompraProductoNuevo", "Precio de venta unitario:")
        )
        self.label_tipo_pago_no_elegido_2.setText(
            _translate("RegistrarCompraProductoNuevo", "$")
        )
        self.eleccion_posnet.setText(
            _translate("RegistrarCompraProductoNuevo", "Posnet")
        )
        self.eleccion_efectivo.setText(
            _translate("RegistrarCompraProductoNuevo", "Efectivo")
        )
        self.boton_volver.setText(_translate("RegistrarCompraProductoNuevo", "Volver"))
        self.eleccion_mercadopago.setText(
            _translate("RegistrarCompraProductoNuevo", "MercadoPago")
        )
        self.label_5.setText(
            _translate("RegistrarCompraProductoNuevo", "Nombre producto:")
        )
        self.label.setText(
            _translate("RegistrarCompraProductoNuevo", "LISTA DE PRODUCTOS")
        )
        self.label_8.setText(
            _translate("RegistrarCompraProductoNuevo", "Costo Unitario:")
        )
        self.label_2.setText(
            _translate("RegistrarCompraProductoNuevo", "Seleccione el tipo de pago:")
        )
