# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registrar_compra_producto_listado.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


from ventanas.imagenes import imagenes


class Ui_RegistrarCompraProductoListado(object):
    def setupUi(self, RegistrarCompraProductoListado):
        RegistrarCompraProductoListado.setObjectName("RegistrarCompraProductoListado")
        RegistrarCompraProductoListado.resize(1195, 877)
        RegistrarCompraProductoListado.setMinimumSize(QtCore.QSize(1195, 877))
        RegistrarCompraProductoListado.setMaximumSize(QtCore.QSize(1195, 877))
        RegistrarCompraProductoListado.setStyleSheet("")
        self.widget = QtWidgets.QWidget(RegistrarCompraProductoListado)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1195, 877))
        self.widget.setMinimumSize(QtCore.QSize(1195, 877))
        self.widget.setMaximumSize(QtCore.QSize(1195, 877))
        self.widget.setStyleSheet(
            "QPushButton{\n"
            'font: 57 11pt "Yu Gothic Medium";\n'
            "color: #fff;\n"
            "padding:5px;\n"
            "    background-color: qlineargradient(spread:pad, x1:0.421, y1:0.636863, x2:1, y2:0, stop:0 rgba(52, 190, 250, 172), stop:1 rgba(255, 255, 255, 158));\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: qlineargradient(spread:pad, x1:0.421, y1:0.636863, x2:1, y2:0, stop:0 rgba(41, 151, 199, 172), stop:1 rgba(255, 255, 255, 158));\n"
            "}\n"
            "QPushButton:pressed {\n"
            "    padding-top: 10px;\n"
            "    padding-left: 10px;\n"
            "}\n"
            "QLineEdit{\n"
            "padding: 3px;\n"
            "color: #fff; \n"
            'font: 11pt "MS Shell Dlg 2";\n'
            "    background-color: qlineargradient(spread:pad, x1:0.421, y1:0.636863, x2:1, y2:0, stop:0 rgba(52, 190, 250, 172), stop:1 rgba(255, 255, 255, 158));\n"
            "}\n"
            "QLineEdit:hover {\n"
            "    background-color: qlineargradient(spread:pad, x1:0.421, y1:0.636863, x2:1, y2:0, stop:0 rgba(41, 151, 199, 172), stop:1 rgba(255, 255, 255, 158));\n"
            "}\n"
            "QLineEdit:focus {\n"
            "    background-color: qlineargradient(spread:pad, x1:0.421, y1:0.636863, x2:1, y2:0, stop:0 rgba(41, 151, 199, 172), stop:1 rgba(255, 255, 255, 158));\n"
            "color:#fff;\n"
            "}\n"
            "QRadioButton{\n"
            "color:#fff;\n"
            "background-color: none;\n"
            'font: 57 14pt "Yu Gothic Medium";\n'
            "}\n"
            "QTreeView{\n"
            "    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(147, 147, 147, 162));\n"
            "color: #fff;\n"
            "border: 1px solid #fff;\n"
            "}\n"
            "QHeaderView::section {\n"
            "color: #000;\n"
            "border: 1px solid #000;\n"
            "}\n"
            "QTreeView::item {\n"
            "color: #fff;\n"
            "}\n"
            "QWidget#widget{\n"
            "    background-image: url(:/registrar_compras/3376284.jpg);\n"
            "}\n"
            "QLabel{\n"
            "color:#fff;\n"
            "}"
        )
        self.widget.setObjectName("widget")
        self.boton_buscar_producto = QtWidgets.QPushButton(self.widget)
        self.boton_buscar_producto.setGeometry(QtCore.QRect(460, 100, 101, 31))
        self.boton_buscar_producto.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_buscar_producto.setStyleSheet("border-radius:10px;")
        self.boton_buscar_producto.setObjectName("boton_buscar_producto")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(920, 160, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.eleccion_efectivo = QtWidgets.QRadioButton(self.widget)
        self.eleccion_efectivo.setGeometry(QtCore.QRect(720, 290, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.eleccion_efectivo.setFont(font)
        self.eleccion_efectivo.setStyleSheet("")
        self.eleccion_efectivo.setObjectName("eleccion_efectivo")
        self.label_tipo_pago_no_elegido_2 = QtWidgets.QLabel(self.widget)
        self.label_tipo_pago_no_elegido_2.setGeometry(QtCore.QRect(940, 190, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_tipo_pago_no_elegido_2.setFont(font)
        self.label_tipo_pago_no_elegido_2.setStyleSheet("")
        self.label_tipo_pago_no_elegido_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tipo_pago_no_elegido_2.setObjectName("label_tipo_pago_no_elegido_2")
        self.input_costo_unitario = QtWidgets.QLineEdit(self.widget)
        self.input_costo_unitario.setGeometry(QtCore.QRect(960, 190, 121, 31))
        self.input_costo_unitario.setStyleSheet("")
        self.input_costo_unitario.setText("")
        self.input_costo_unitario.setFrame(True)
        self.input_costo_unitario.setAlignment(QtCore.Qt.AlignCenter)
        self.input_costo_unitario.setObjectName("input_costo_unitario")
        self.producto_no_encontrado = QtWidgets.QLabel(self.widget)
        self.producto_no_encontrado.setGeometry(QtCore.QRect(160, 130, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.producto_no_encontrado.setFont(font)
        self.producto_no_encontrado.setStyleSheet("color:#f00;")
        self.producto_no_encontrado.setText("")
        self.producto_no_encontrado.setObjectName("producto_no_encontrado")
        self.label_producto_no_seleccionado = QtWidgets.QLabel(self.widget)
        self.label_producto_no_seleccionado.setGeometry(QtCore.QRect(980, 340, 141, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_producto_no_seleccionado.setFont(font)
        self.label_producto_no_seleccionado.setStyleSheet("color:#f00;")
        self.label_producto_no_seleccionado.setText("")
        self.label_producto_no_seleccionado.setAlignment(QtCore.Qt.AlignCenter)
        self.label_producto_no_seleccionado.setWordWrap(True)
        self.label_producto_no_seleccionado.setObjectName(
            "label_producto_no_seleccionado"
        )
        self.eleccion_posnet = QtWidgets.QRadioButton(self.widget)
        self.eleccion_posnet.setGeometry(QtCore.QRect(860, 290, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.eleccion_posnet.setFont(font)
        self.eleccion_posnet.setStyleSheet("")
        self.eleccion_posnet.setObjectName("eleccion_posnet")
        self.input_cantidad_comprada = QtWidgets.QLineEdit(self.widget)
        self.input_cantidad_comprada.setGeometry(QtCore.QRect(750, 190, 71, 31))
        self.input_cantidad_comprada.setStyleSheet("")
        self.input_cantidad_comprada.setText("")
        self.input_cantidad_comprada.setFrame(True)
        self.input_cantidad_comprada.setAlignment(QtCore.Qt.AlignCenter)
        self.input_cantidad_comprada.setObjectName("input_cantidad_comprada")
        self.treeview_compras = QtWidgets.QTreeView(self.widget)
        self.treeview_compras.setGeometry(QtCore.QRect(620, 430, 561, 421))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.treeview_compras.setFont(font)
        self.treeview_compras.setStyleSheet("")
        self.treeview_compras.setAllColumnsShowFocus(False)
        self.treeview_compras.setObjectName("treeview_compras")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(60, 40, 491, 41))
        self.label.setStyleSheet(
            'font: 36pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label.setObjectName("label")
        self.boton_volver = QtWidgets.QPushButton(self.widget)
        self.boton_volver.setGeometry(QtCore.QRect(1090, 20, 101, 31))
        self.boton_volver.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_volver.setStyleSheet("")
        self.boton_volver.setObjectName("boton_volver")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(710, 160, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.boton_registrar_compra = QtWidgets.QPushButton(self.widget)
        self.boton_registrar_compra.setGeometry(QtCore.QRect(840, 350, 131, 41))
        self.boton_registrar_compra.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_registrar_compra.setStyleSheet("")
        self.boton_registrar_compra.setObjectName("boton_registrar_compra")
        self.label_error_al_registrar = QtWidgets.QLabel(self.widget)
        self.label_error_al_registrar.setGeometry(QtCore.QRect(690, 360, 151, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_error_al_registrar.setFont(font)
        self.label_error_al_registrar.setStyleSheet("color:#f00;")
        self.label_error_al_registrar.setText("")
        self.label_error_al_registrar.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error_al_registrar.setObjectName("label_error_al_registrar")
        self.treeview_productos = QtWidgets.QTreeView(self.widget)
        self.treeview_productos.setGeometry(QtCore.QRect(20, 160, 591, 691))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.treeview_productos.setFont(font)
        self.treeview_productos.setStyleSheet("")
        self.treeview_productos.setAllColumnsShowFocus(False)
        self.treeview_productos.setObjectName("treeview_productos")
        self.eleccion_mercadopago = QtWidgets.QRadioButton(self.widget)
        self.eleccion_mercadopago.setGeometry(QtCore.QRect(980, 290, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.eleccion_mercadopago.setFont(font)
        self.eleccion_mercadopago.setStyleSheet("")
        self.eleccion_mercadopago.setObjectName("eleccion_mercadopago")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(790, 260, 251, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.input_buscar_producto = QtWidgets.QLineEdit(self.widget)
        self.input_buscar_producto.setGeometry(QtCore.QRect(40, 100, 411, 31))
        self.input_buscar_producto.setStyleSheet("")
        self.input_buscar_producto.setText("")
        self.input_buscar_producto.setAlignment(QtCore.Qt.AlignCenter)
        self.input_buscar_producto.setObjectName("input_buscar_producto")

        self.retranslateUi(RegistrarCompraProductoListado)
        QtCore.QMetaObject.connectSlotsByName(RegistrarCompraProductoListado)

    def retranslateUi(self, RegistrarCompraProductoListado):
        _translate = QtCore.QCoreApplication.translate
        RegistrarCompraProductoListado.setWindowTitle(
            _translate("RegistrarCompraProductoListado", "Form")
        )
        self.boton_buscar_producto.setText(
            _translate("RegistrarCompraProductoListado", "BUSCAR")
        )
        self.label_8.setText(
            _translate("RegistrarCompraProductoListado", "Costo Unitario del producto:")
        )
        self.eleccion_efectivo.setText(
            _translate("RegistrarCompraProductoListado", "Efectivo")
        )
        self.label_tipo_pago_no_elegido_2.setText(
            _translate("RegistrarCompraProductoListado", "$")
        )
        self.eleccion_posnet.setText(
            _translate("RegistrarCompraProductoListado", "Posnet")
        )
        self.label.setText(
            _translate("RegistrarCompraProductoListado", "LISTA DE PRODUCTOS")
        )
        self.boton_volver.setText(
            _translate("RegistrarCompraProductoListado", "VOLVER")
        )
        self.label_7.setText(
            _translate("RegistrarCompraProductoListado", "Cantidad comprada:")
        )
        self.boton_registrar_compra.setText(
            _translate("RegistrarCompraProductoListado", "REGISTRAR")
        )
        self.eleccion_mercadopago.setText(
            _translate("RegistrarCompraProductoListado", "MercadoPago")
        )
        self.label_2.setText(
            _translate("RegistrarCompraProductoListado", "Seleccione el tipo de pago:")
        )
