# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registrar_ventas_vendedor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from ventanas.imagenes import imagenes


class Ui_RegistrarVentaVendedor(object):
    def setupUi(self, RegistrarVentaVendedor):
        RegistrarVentaVendedor.setObjectName("RegistrarVentaVendedor")
        RegistrarVentaVendedor.resize(1195, 877)
        RegistrarVentaVendedor.setMinimumSize(QtCore.QSize(1195, 877))
        RegistrarVentaVendedor.setMaximumSize(QtCore.QSize(1195, 877))
        RegistrarVentaVendedor.setStyleSheet("")
        self.widget = QtWidgets.QWidget(RegistrarVentaVendedor)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1195, 877))
        self.widget.setMinimumSize(QtCore.QSize(1195, 877))
        self.widget.setMaximumSize(QtCore.QSize(1195, 877))
        self.widget.setStyleSheet(
            "QPushButton{\n"
            'font: 57 11pt "Yu Gothic Medium";\n'
            "color: #fff;\n"
            "padding:5px;\n"
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 255), stop:0.0568182 rgba(0, 0, 0, 255), stop:1 rgba(0, 142, 133, 255));\n"
            "}\n"
            "QPushButton:hover {\n"
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.118644 rgba(0, 100, 0, 243), stop:1 rgba(255, 255, 255, 255));\n"
            "}\n"
            "QPushButton:pressed {\n"
            "    padding-top: 10px;\n"
            "    padding-left: 10px;\n"
            "}\n"
            "QLineEdit{\n"
            "padding: 3px;\n"
            "color: #fff; \n"
            'font: 11pt "MS Shell Dlg 2";\n'
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 255), stop:0.0568182 rgba(0, 0, 0, 255), stop:1 rgba(0, 142, 133, 255));\n"
            "}\n"
            "QLineEdit:hover {\n"
            "background-color:none;\n"
            "}\n"
            "QLineEdit:focus {\n"
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.118644 rgba(0, 100, 0, 243), stop:1 rgba(255, 255, 255, 255));\n"
            "}\n"
            "QWidget#widget{\n"
            "background-image: url(:/registrar_ventas/3294425.jpg);\n"
            "}\n"
            "QRadioButton{\n"
            "color: #fff;\n"
            "background-color: none;\n"
            'font: 57 14pt "Yu Gothic Medium";\n'
            "}\n"
            "QTreeView{\n"
            "    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(163, 163, 163, 113));\n"
            "color: #000;\n"
            "border: 1px solid #000;\n"
            "}\n"
            "QHeaderView::section {\n"
            "color: #000;\n"
            "border: 1px solid #000;\n"
            "}\n"
            "QTreeView::item {\n"
            "color: #fff;\n"
            "}"
        )
        self.widget.setObjectName("widget")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(830, 120, 181, 21))
        self.label_5.setStyleSheet(
            "\n"
            'font: 57 16pt "Yu Gothic Medium";\n'
            "color: #fff;\n"
            "background: none;"
        )
        self.label_5.setObjectName("label_5")
        self.label_cantidad_invalida = QtWidgets.QLabel(self.widget)
        self.label_cantidad_invalida.setGeometry(QtCore.QRect(690, 190, 451, 31))
        self.label_cantidad_invalida.setStyleSheet(
            "\n"
            'font: 57 14pt "Yu Gothic Medium";\n'
            "color: #f00;\n"
            "background: none;"
        )
        self.label_cantidad_invalida.setText("")
        self.label_cantidad_invalida.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cantidad_invalida.setObjectName("label_cantidad_invalida")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(780, 230, 271, 31))
        self.label_6.setStyleSheet(
            "\n"
            'font: 57 16pt "Yu Gothic Medium";\n'
            "color: #fff;\n"
            "background: none;"
        )
        self.label_6.setObjectName("label_6")
        self.eleccion_efectivo = QtWidgets.QRadioButton(self.widget)
        self.eleccion_efectivo.setGeometry(QtCore.QRect(720, 260, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.eleccion_efectivo.setFont(font)
        self.eleccion_efectivo.setStyleSheet("")
        self.eleccion_efectivo.setObjectName("eleccion_efectivo")
        self.eleccion_mercadopago = QtWidgets.QRadioButton(self.widget)
        self.eleccion_mercadopago.setGeometry(QtCore.QRect(980, 260, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.eleccion_mercadopago.setFont(font)
        self.eleccion_mercadopago.setStyleSheet("")
        self.eleccion_mercadopago.setObjectName("eleccion_mercadopago")
        self.input_cantidad_vendida = QtWidgets.QLineEdit(self.widget)
        self.input_cantidad_vendida.setGeometry(QtCore.QRect(880, 150, 71, 41))
        self.input_cantidad_vendida.setStyleSheet("")
        self.input_cantidad_vendida.setText("")
        self.input_cantidad_vendida.setFrame(True)
        self.input_cantidad_vendida.setAlignment(QtCore.Qt.AlignCenter)
        self.input_cantidad_vendida.setDragEnabled(False)
        self.input_cantidad_vendida.setClearButtonEnabled(False)
        self.input_cantidad_vendida.setObjectName("input_cantidad_vendida")
        self.treeview_productos = QtWidgets.QTreeView(self.widget)
        self.treeview_productos.setGeometry(QtCore.QRect(10, 160, 621, 691))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.treeview_productos.setFont(font)
        self.treeview_productos.setStyleSheet("")
        self.treeview_productos.setAllColumnsShowFocus(False)
        self.treeview_productos.setObjectName("treeview_productos")
        self.eleccion_posnet = QtWidgets.QRadioButton(self.widget)
        self.eleccion_posnet.setGeometry(QtCore.QRect(860, 260, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.eleccion_posnet.setFont(font)
        self.eleccion_posnet.setStyleSheet("")
        self.eleccion_posnet.setObjectName("eleccion_posnet")
        self.boton_registrar_venta = QtWidgets.QPushButton(self.widget)
        self.boton_registrar_venta.setGeometry(QtCore.QRect(840, 340, 141, 41))
        self.boton_registrar_venta.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_registrar_venta.setStyleSheet("")
        self.boton_registrar_venta.setObjectName("boton_registrar_venta")
        self.label_tipo_pago_no_elegido = QtWidgets.QLabel(self.widget)
        self.label_tipo_pago_no_elegido.setGeometry(QtCore.QRect(690, 300, 451, 31))
        self.label_tipo_pago_no_elegido.setStyleSheet(
            'font: 57 14pt "Yu Gothic Medium";\n' "color: #f00;\n" "background: none;"
        )
        self.label_tipo_pago_no_elegido.setText("")
        self.label_tipo_pago_no_elegido.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tipo_pago_no_elegido.setObjectName("label_tipo_pago_no_elegido")
        self.treeview_ventas = QtWidgets.QTreeView(self.widget)
        self.treeview_ventas.setGeometry(QtCore.QRect(640, 420, 541, 431))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.treeview_ventas.setFont(font)
        self.treeview_ventas.setStyleSheet("")
        self.treeview_ventas.setAllColumnsShowFocus(False)
        self.treeview_ventas.setObjectName("treeview_ventas")
        self.producto_no_encontrado = QtWidgets.QLabel(self.widget)
        self.producto_no_encontrado.setGeometry(QtCore.QRect(160, 130, 231, 31))
        self.producto_no_encontrado.setStyleSheet(
            'font: 57 14pt "Yu Gothic Medium";\n' "color: #f00;\n" "background: none;"
        )
        self.producto_no_encontrado.setText("")
        self.producto_no_encontrado.setObjectName("producto_no_encontrado")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(60, 40, 491, 41))
        self.label.setStyleSheet(
            'font: 36pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label.setObjectName("label")
        self.boton_buscar_producto = QtWidgets.QPushButton(self.widget)
        self.boton_buscar_producto.setGeometry(QtCore.QRect(490, 100, 101, 31))
        self.boton_buscar_producto.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_buscar_producto.setStyleSheet("border-radius: 7px;")
        self.boton_buscar_producto.setObjectName("boton_buscar_producto")
        self.input_buscar_producto = QtWidgets.QLineEdit(self.widget)
        self.input_buscar_producto.setGeometry(QtCore.QRect(70, 100, 411, 31))
        self.input_buscar_producto.setStyleSheet("")
        self.input_buscar_producto.setText("")
        self.input_buscar_producto.setAlignment(QtCore.Qt.AlignCenter)
        self.input_buscar_producto.setObjectName("input_buscar_producto")

        self.retranslateUi(RegistrarVentaVendedor)
        QtCore.QMetaObject.connectSlotsByName(RegistrarVentaVendedor)

    def retranslateUi(self, RegistrarVentaVendedor):
        _translate = QtCore.QCoreApplication.translate
        RegistrarVentaVendedor.setWindowTitle(
            _translate("RegistrarVentaVendedor", "Form")
        )
        self.label_5.setText(_translate("RegistrarVentaVendedor", "Cantidad Vendida:"))
        self.label_6.setText(
            _translate("RegistrarVentaVendedor", "Seleccione el tipo de pago:")
        )
        self.eleccion_efectivo.setText(_translate("RegistrarVentaVendedor", "Efectivo"))
        self.eleccion_mercadopago.setText(
            _translate("RegistrarVentaVendedor", "MercadoPago")
        )
        self.eleccion_posnet.setText(_translate("RegistrarVentaVendedor", "Posnet"))
        self.boton_registrar_venta.setText(
            _translate("RegistrarVentaVendedor", "REGISTRAR")
        )
        self.label.setText(_translate("RegistrarVentaVendedor", "LISTA DE PRODUCTOS"))
        self.boton_buscar_producto.setText(
            _translate("RegistrarVentaVendedor", "Buscar")
        )
