# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stock_cregar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ventanas.imagenes import imagenes
from PyQt5.QtCore import Qt


class Ui_StockCregar(object):
    def setupUi(self, StockCregar):
        StockCregar.setObjectName("StockCregar")
        StockCregar.resize(1195, 645)
        StockCregar.setMinimumSize(QtCore.QSize(1195, 645))
        StockCregar.setMaximumSize(QtCore.QSize(1195, 645))
        StockCregar.setStyleSheet("")
        self.widget = QtWidgets.QWidget(StockCregar)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1195, 722))
        self.widget.setMinimumSize(QtCore.QSize(1195, 722))
        self.widget.setMaximumSize(QtCore.QSize(1195, 722))
        self.widget.setStyleSheet(
            "QPushButton{\n"
            "border:2px solid rgb(28, 165, 206);\n"
            "border-radius: 10px;\n"
            "color: #fff;\n"
            'font: 57 12pt "Yu Gothic Medium";\n'
            "padding:5px;\n"
            "background-color:none;\n"
            "}\n"
            "QPushButton:hover {\n"
            "color: rgb(28, 165, 206);\n"
            "border:1px solid #fff;\n"
            "}\n"
            "QPushButton:pressed {\n"
            "    padding-top: 10px;\n"
            "    padding-left: 10px;\n"
            "}\n"
            "\n"
            "QLineEdit{\n"
            "background-color:transparent;\n"
            "border-bottom:2px solid rgb(28, 165, 206);\n"
            "border-radius: 0px;\n"
            "padding: 4px;\n"
            "color: #fff;\n"
            "}\n"
            "QLineEdit:hover {\n"
            "background-color:transparent;\n"
            "}\n"
            "QLineEdit:focus {\n"
            "background-color:transparent;\n"
            "}\n"
            "QWidget#widget{\n"
            "background-image: url(:/stock_disponible/modern-2560-x-1600-background-od87qg1wfx087jbt.jpg);\n"
            "}\n"
            "QTreeView{\n"
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 190, 255, 113));\n"
            "color: #fff;\n"
            "border: 1px solid #000;\n"
            "}\n"
            "QHeaderView::section {\n"
            "color: #000;\n"
            "border: 1px solid #000;\n"
            "font-size: 15px;\n"
            "}\n"
            "QTreeView::item {\n"
            "color: #fff;\n"
            "border-right: 0.5px solid #000;\n"
            "border-bottom: 0.5px solid #000;\n"
            "}\n"
            "QTreeView::item:selected {\n"
            "background-color: #f00;\n"
            "}\n"
            ""
        )
        self.widget.setObjectName("widget")
        self.widget_lista_productos = QtWidgets.QWidget(self.widget)
        self.widget_lista_productos.setGeometry(QtCore.QRect(0, 0, 1201, 721))
        self.widget_lista_productos.setStyleSheet("")
        self.widget_lista_productos.setObjectName("widget_lista_productos")
        self.label_15 = QtWidgets.QLabel(self.widget_lista_productos)
        self.label_15.setGeometry(QtCore.QRect(420, 0, 341, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setStyleSheet(
            'font: 20pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.input_buscar_producto = QtWidgets.QLineEdit(self.widget_lista_productos)
        self.input_buscar_producto.setGeometry(QtCore.QRect(410, 40, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.input_buscar_producto.setFont(font)
        self.input_buscar_producto.setStyleSheet("")
        self.input_buscar_producto.setAlignment(QtCore.Qt.AlignCenter)
        self.input_buscar_producto.setObjectName("input_buscar_producto")
        self.boton_buscar_producto = QtWidgets.QPushButton(self.widget_lista_productos)
        self.boton_buscar_producto.setGeometry(QtCore.QRect(780, 40, 101, 31))
        self.boton_buscar_producto.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_buscar_producto.setStyleSheet("")
        self.boton_buscar_producto.setObjectName("boton_buscar_producto")
        self.boton_volver = QtWidgets.QPushButton(self.widget_lista_productos)
        self.boton_volver.setGeometry(QtCore.QRect(1090, 20, 91, 31))
        self.boton_volver.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_volver.setStyleSheet("")
        self.boton_volver.setObjectName("boton_volver")
        self.treeview_productos = QtWidgets.QTreeView(self.widget_lista_productos)
        self.treeview_productos.setGeometry(QtCore.QRect(0, 80, 1191, 471))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.treeview_productos.setFont(font)
        self.treeview_productos.setStyleSheet("")
        self.treeview_productos.setObjectName("treeview_productos")
        self.treeview_productos.setFocusPolicy(Qt.NoFocus)

        self.modelo_productos = QtGui.QStandardItemModel()
        self.modelo_productos.setHorizontalHeaderLabels(
            [
                "ID",
                "Producto",
                "Stock",
                "Costo Inicial",
                "desc 1",
                "Costo Parc 1",
                "IVA",
                "Costo Parc 2",
                "desc 2",
                "Costo Neto",
                "Aumento Ef",
                "Efectivo",
                "Aumento ML",
                "MercadoLibre",
                "Aumento Cons",
                "Constructores",
            ]
        )
        header = self.treeview_productos.header()
        header.setDefaultAlignment(QtCore.Qt.AlignHCenter)
        header.setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)

        self.producto_no_encontrado = QtWidgets.QLabel(self.widget_lista_productos)
        self.producto_no_encontrado.setGeometry(QtCore.QRect(230, 50, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.producto_no_encontrado.setFont(font)
        self.producto_no_encontrado.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.producto_no_encontrado.setStyleSheet(
            'font: 57 12pt "Yu Gothic Medium";\n' "color: #f00;\n" "background: none;"
        )
        self.producto_no_encontrado.setText("")
        self.producto_no_encontrado.setAlignment(QtCore.Qt.AlignCenter)
        self.producto_no_encontrado.setObjectName("producto_no_encontrado")
        self.boton_agregar_producto = QtWidgets.QPushButton(self.widget_lista_productos)
        self.boton_agregar_producto.setGeometry(QtCore.QRect(110, 560, 201, 51))
        self.boton_agregar_producto.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_agregar_producto.setStyleSheet("")
        self.boton_agregar_producto.setObjectName("boton_agregar_producto")
        self.boton_eliminar_producto = QtWidgets.QPushButton(
            self.widget_lista_productos
        )
        self.boton_eliminar_producto.setGeometry(QtCore.QRect(370, 560, 201, 51))
        self.boton_eliminar_producto.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_eliminar_producto.setStyleSheet("")
        self.boton_eliminar_producto.setObjectName("boton_eliminar_producto")
        self.boton_modificar_producto = QtWidgets.QPushButton(
            self.widget_lista_productos
        )
        self.boton_modificar_producto.setGeometry(QtCore.QRect(650, 560, 201, 51))
        self.boton_modificar_producto.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_modificar_producto.setStyleSheet("")
        self.boton_modificar_producto.setObjectName("boton_modificar_producto")
        self.boton_modificar_productos_gral = QtWidgets.QPushButton(
            self.widget_lista_productos
        )
        self.boton_modificar_productos_gral.setGeometry(QtCore.QRect(910, 560, 201, 51))
        self.boton_modificar_productos_gral.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_modificar_productos_gral.setStyleSheet("")
        self.boton_modificar_productos_gral.setObjectName(
            "boton_modificar_productos_gral"
        )
        self.label_eliminar_producto = QtWidgets.QLabel(self.widget_lista_productos)
        self.label_eliminar_producto.setGeometry(QtCore.QRect(350, 610, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_eliminar_producto.setFont(font)
        self.label_eliminar_producto.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_eliminar_producto.setStyleSheet(
            'font: 57 12pt "Yu Gothic Medium";\n' "color: #f00;\n" "background: none;"
        )
        self.label_eliminar_producto.setText("")
        self.label_eliminar_producto.setAlignment(QtCore.Qt.AlignCenter)
        self.label_eliminar_producto.setObjectName("label_eliminar_producto")
        self.label_modificar_producto = QtWidgets.QLabel(self.widget_lista_productos)
        self.label_modificar_producto.setGeometry(QtCore.QRect(620, 610, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_modificar_producto.setFont(font)
        self.label_modificar_producto.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_modificar_producto.setStyleSheet(
            'font: 57 12pt "Yu Gothic Medium";\n' "color: #f00;\n" "background: none;"
        )
        self.label_modificar_producto.setText("")
        self.label_modificar_producto.setAlignment(QtCore.Qt.AlignCenter)
        self.label_modificar_producto.setObjectName("label_modificar_producto")
        self.widget_agregar_producto = QtWidgets.QWidget(self.widget)
        self.widget_agregar_producto.setGeometry(QtCore.QRect(140, 10, 951, 621))
        self.widget_agregar_producto.setStyleSheet("")
        self.widget_agregar_producto.setObjectName("widget_agregar_producto")
        self.input_nombre_producto = QtWidgets.QLineEdit(self.widget_agregar_producto)
        self.input_nombre_producto.setGeometry(QtCore.QRect(20, 90, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.input_nombre_producto.setFont(font)
        self.input_nombre_producto.setStyleSheet("")
        self.input_nombre_producto.setText("")
        self.input_nombre_producto.setAlignment(QtCore.Qt.AlignCenter)
        self.input_nombre_producto.setObjectName("input_nombre_producto")
        self.input_stock = QtWidgets.QLineEdit(self.widget_agregar_producto)
        self.input_stock.setGeometry(QtCore.QRect(190, 190, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.input_stock.setFont(font)
        self.input_stock.setStyleSheet("")
        self.input_stock.setAlignment(QtCore.Qt.AlignCenter)
        self.input_stock.setObjectName("input_stock")
        self.input_descuento_1 = QtWidgets.QLineEdit(self.widget_agregar_producto)
        self.input_descuento_1.setGeometry(QtCore.QRect(730, 90, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.input_descuento_1.setFont(font)
        self.input_descuento_1.setStyleSheet("")
        self.input_descuento_1.setAlignment(QtCore.Qt.AlignCenter)
        self.input_descuento_1.setObjectName("input_descuento_1")
        self.boton_cancelar_modificacion = QtWidgets.QPushButton(
            self.widget_agregar_producto
        )
        self.boton_cancelar_modificacion.setGeometry(QtCore.QRect(10, 570, 91, 31))
        self.boton_cancelar_modificacion.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_cancelar_modificacion.setStyleSheet("")
        self.boton_cancelar_modificacion.setObjectName("boton_cancelar_modificacion")
        self.input_aumento_efectivo = QtWidgets.QLineEdit(self.widget_agregar_producto)
        self.input_aumento_efectivo.setGeometry(QtCore.QRect(180, 440, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.input_aumento_efectivo.setFont(font)
        self.input_aumento_efectivo.setStyleSheet("")
        self.input_aumento_efectivo.setAlignment(QtCore.Qt.AlignCenter)
        self.input_aumento_efectivo.setObjectName("input_aumento_efectivo")
        self.input_costo_inicial = QtWidgets.QLineEdit(self.widget_agregar_producto)
        self.input_costo_inicial.setGeometry(QtCore.QRect(180, 300, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.input_costo_inicial.setFont(font)
        self.input_costo_inicial.setStyleSheet("")
        self.input_costo_inicial.setAlignment(QtCore.Qt.AlignCenter)
        self.input_costo_inicial.setObjectName("input_costo_inicial")
        self.input_aumento_constructores = QtWidgets.QLineEdit(
            self.widget_agregar_producto
        )
        self.input_aumento_constructores.setGeometry(QtCore.QRect(720, 440, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.input_aumento_constructores.setFont(font)
        self.input_aumento_constructores.setStyleSheet("")
        self.input_aumento_constructores.setAlignment(QtCore.Qt.AlignCenter)
        self.input_aumento_constructores.setObjectName("input_aumento_constructores")
        self.input_aumento_mercadolibre = QtWidgets.QLineEdit(
            self.widget_agregar_producto
        )
        self.input_aumento_mercadolibre.setGeometry(QtCore.QRect(450, 440, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.input_aumento_mercadolibre.setFont(font)
        self.input_aumento_mercadolibre.setStyleSheet("")
        self.input_aumento_mercadolibre.setAlignment(QtCore.Qt.AlignCenter)
        self.input_aumento_mercadolibre.setObjectName("input_aumento_mercadolibre")
        self.label_16 = QtWidgets.QLabel(self.widget_agregar_producto)
        self.label_16.setGeometry(QtCore.QRect(190, 60, 81, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setStyleSheet(
            'font: 13pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.widget_agregar_producto)
        self.label_17.setGeometry(QtCore.QRect(190, 150, 81, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setStyleSheet(
            'font: 13pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.widget_agregar_producto)
        self.label_18.setGeometry(QtCore.QRect(180, 260, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_18.setStyleSheet(
            'font: 13pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.widget_agregar_producto)
        self.label_19.setGeometry(QtCore.QRect(710, 60, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setStyleSheet(
            'font: 13pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.widget_agregar_producto)
        self.label_20.setGeometry(QtCore.QRect(710, 260, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_20.setStyleSheet(
            'font: 13pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.widget_agregar_producto)
        self.label_21.setGeometry(QtCore.QRect(120, 400, 181, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_21.setStyleSheet(
            'font: 13pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.widget_agregar_producto)
        self.label_22.setGeometry(QtCore.QRect(390, 400, 171, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_22.setStyleSheet(
            'font: 13pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.widget_agregar_producto)
        self.label_23.setGeometry(QtCore.QRect(710, 160, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_23.setStyleSheet(
            'font: 13pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.widget_agregar_producto)
        self.label_24.setGeometry(QtCore.QRect(660, 400, 181, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_24.setStyleSheet(
            'font: 13pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.boton_confirmar_registro = QtWidgets.QPushButton(
            self.widget_agregar_producto
        )
        self.boton_confirmar_registro.setGeometry(QtCore.QRect(420, 520, 131, 51))
        self.boton_confirmar_registro.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_confirmar_registro.setStyleSheet("")
        self.boton_confirmar_registro.setObjectName("boton_confirmar_registro")
        self.label_25 = QtWidgets.QLabel(self.widget_agregar_producto)
        self.label_25.setGeometry(QtCore.QRect(160, 300, 21, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_25.setStyleSheet(
            'font: 13pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.widget_agregar_producto)
        self.label_26.setGeometry(QtCore.QRect(790, 100, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_26.setStyleSheet(
            'font: 13pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.widget_agregar_producto)
        self.label_27.setGeometry(QtCore.QRect(790, 300, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_27.setStyleSheet(
            'font: 13pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.widget_agregar_producto)
        self.label_28.setGeometry(QtCore.QRect(790, 200, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_28.setStyleSheet(
            'font: 13pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.input_iva = QtWidgets.QLineEdit(self.widget_agregar_producto)
        self.input_iva.setGeometry(QtCore.QRect(730, 190, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.input_iva.setFont(font)
        self.input_iva.setStyleSheet("")
        self.input_iva.setAlignment(QtCore.Qt.AlignCenter)
        self.input_iva.setObjectName("input_iva")
        self.input_descuento_2 = QtWidgets.QLineEdit(self.widget_agregar_producto)
        self.input_descuento_2.setGeometry(QtCore.QRect(730, 290, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.input_descuento_2.setFont(font)
        self.input_descuento_2.setStyleSheet("")
        self.input_descuento_2.setAlignment(QtCore.Qt.AlignCenter)
        self.input_descuento_2.setObjectName("input_descuento_2")
        self.label_29 = QtWidgets.QLabel(self.widget_agregar_producto)
        self.label_29.setGeometry(QtCore.QRect(240, 450, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_29.setStyleSheet(
            'font: 13pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.widget_agregar_producto)
        self.label_30.setGeometry(QtCore.QRect(510, 450, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_30.setStyleSheet(
            'font: 13pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.widget_agregar_producto)
        self.label_31.setGeometry(QtCore.QRect(780, 450, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_31.setStyleSheet(
            'font: 13pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.boton_confirmar_modificacion = QtWidgets.QPushButton(
            self.widget_agregar_producto
        )
        self.boton_confirmar_modificacion.setGeometry(QtCore.QRect(420, 520, 131, 51))
        self.boton_confirmar_modificacion.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_confirmar_modificacion.setStyleSheet("")
        self.boton_confirmar_modificacion.setObjectName("boton_confirmar_modificacion")
        self.label_error = QtWidgets.QLabel(self.widget_agregar_producto)
        self.label_error.setGeometry(QtCore.QRect(240, 530, 171, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_error.setFont(font)
        self.label_error.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_error.setStyleSheet(
            'font: 13pt "MS Shell Dlg 2";\n' "color: #f00;\n" "background: none;"
        )
        self.label_error.setText("")
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.widget_modificar_gral = QtWidgets.QWidget(self.widget)
        self.widget_modificar_gral.setGeometry(QtCore.QRect(180, 130, 821, 461))
        self.widget_modificar_gral.setStyleSheet("")
        self.widget_modificar_gral.setObjectName("widget_modificar_gral")
        self.label_32 = QtWidgets.QLabel(self.widget_modificar_gral)
        self.label_32.setGeometry(QtCore.QRect(240, 20, 331, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_32.setStyleSheet(
            'font: 20pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.boton_modificar_costo_inicial = QtWidgets.QPushButton(
            self.widget_modificar_gral
        )
        self.boton_modificar_costo_inicial.setGeometry(QtCore.QRect(120, 70, 241, 51))
        self.boton_modificar_costo_inicial.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_modificar_costo_inicial.setStyleSheet("")
        self.boton_modificar_costo_inicial.setObjectName(
            "boton_modificar_costo_inicial"
        )
        self.boton_modificar_descuento_1 = QtWidgets.QPushButton(
            self.widget_modificar_gral
        )
        self.boton_modificar_descuento_1.setGeometry(QtCore.QRect(440, 70, 241, 51))
        self.boton_modificar_descuento_1.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_modificar_descuento_1.setStyleSheet("")
        self.boton_modificar_descuento_1.setObjectName("boton_modificar_descuento_1")
        self.boton_modificar_descuento_2 = QtWidgets.QPushButton(
            self.widget_modificar_gral
        )
        self.boton_modificar_descuento_2.setGeometry(QtCore.QRect(440, 130, 241, 51))
        self.boton_modificar_descuento_2.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_modificar_descuento_2.setStyleSheet("")
        self.boton_modificar_descuento_2.setObjectName("boton_modificar_descuento_2")
        self.boton_modificar_iva = QtWidgets.QPushButton(self.widget_modificar_gral)
        self.boton_modificar_iva.setGeometry(QtCore.QRect(120, 130, 241, 51))
        self.boton_modificar_iva.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_modificar_iva.setStyleSheet("")
        self.boton_modificar_iva.setObjectName("boton_modificar_iva")
        self.boton_modificar_aumento_constructores = QtWidgets.QPushButton(
            self.widget_modificar_gral
        )
        self.boton_modificar_aumento_constructores.setGeometry(
            QtCore.QRect(540, 190, 241, 51)
        )
        self.boton_modificar_aumento_constructores.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_modificar_aumento_constructores.setStyleSheet("")
        self.boton_modificar_aumento_constructores.setObjectName(
            "boton_modificar_aumento_constructores"
        )
        self.boton_modificar_aumento_efectivo = QtWidgets.QPushButton(
            self.widget_modificar_gral
        )
        self.boton_modificar_aumento_efectivo.setGeometry(
            QtCore.QRect(20, 190, 241, 51)
        )
        self.boton_modificar_aumento_efectivo.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_modificar_aumento_efectivo.setStyleSheet("")
        self.boton_modificar_aumento_efectivo.setObjectName(
            "boton_modificar_aumento_efectivo"
        )
        self.boton_modificar_aumento_mercadolibre = QtWidgets.QPushButton(
            self.widget_modificar_gral
        )
        self.boton_modificar_aumento_mercadolibre.setGeometry(
            QtCore.QRect(280, 190, 241, 51)
        )
        self.boton_modificar_aumento_mercadolibre.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_modificar_aumento_mercadolibre.setStyleSheet("")
        self.boton_modificar_aumento_mercadolibre.setObjectName(
            "boton_modificar_aumento_mercadolibre"
        )
        self.boton_cancelar_modificacion_gral = QtWidgets.QPushButton(
            self.widget_modificar_gral
        )
        self.boton_cancelar_modificacion_gral.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.boton_cancelar_modificacion_gral.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_cancelar_modificacion_gral.setStyleSheet("")
        self.boton_cancelar_modificacion_gral.setObjectName(
            "boton_cancelar_modificacion_gral"
        )
        self.widget_ingresar_porcentaje = QtWidgets.QWidget(self.widget_modificar_gral)
        self.widget_ingresar_porcentaje.setGeometry(QtCore.QRect(210, 250, 371, 201))
        self.widget_ingresar_porcentaje.setObjectName("widget_ingresar_porcentaje")
        self.label_ingrese_porcentaje = QtWidgets.QLabel(
            self.widget_ingresar_porcentaje
        )
        self.label_ingrese_porcentaje.setGeometry(QtCore.QRect(20, 0, 331, 81))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_ingrese_porcentaje.setFont(font)
        self.label_ingrese_porcentaje.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_ingrese_porcentaje.setStyleSheet(
            'font: 14pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_ingrese_porcentaje.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ingrese_porcentaje.setWordWrap(True)
        self.label_ingrese_porcentaje.setObjectName("label_ingrese_porcentaje")
        self.input_nuevo_porcentaje = QtWidgets.QLineEdit(
            self.widget_ingresar_porcentaje
        )
        self.input_nuevo_porcentaje.setGeometry(QtCore.QRect(150, 90, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.input_nuevo_porcentaje.setFont(font)
        self.input_nuevo_porcentaje.setStyleSheet("")
        self.input_nuevo_porcentaje.setAlignment(QtCore.Qt.AlignCenter)
        self.input_nuevo_porcentaje.setObjectName("input_nuevo_porcentaje")
        self.label_35 = QtWidgets.QLabel(self.widget_ingresar_porcentaje)
        self.label_35.setGeometry(QtCore.QRect(210, 100, 21, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_35.setStyleSheet(
            'font: 13pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.boton_confirmar_modificacion_gral = QtWidgets.QPushButton(
            self.widget_ingresar_porcentaje
        )
        self.boton_confirmar_modificacion_gral.setGeometry(
            QtCore.QRect(120, 150, 121, 51)
        )
        self.boton_confirmar_modificacion_gral.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_confirmar_modificacion_gral.setStyleSheet("")
        self.boton_confirmar_modificacion_gral.setObjectName(
            "boton_confirmar_modificacion_gral"
        )
        self.label_ingrese_porcentaje_valido = QtWidgets.QLabel(
            self.widget_ingresar_porcentaje
        )
        self.label_ingrese_porcentaje_valido.setGeometry(QtCore.QRect(40, 80, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_ingrese_porcentaje_valido.setFont(font)
        self.label_ingrese_porcentaje_valido.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_ingrese_porcentaje_valido.setStyleSheet(
            'font: 10pt "MS Shell Dlg 2";\n' "color: #f00;\n" "background: none;"
        )
        self.label_ingrese_porcentaje_valido.setText("")
        self.label_ingrese_porcentaje_valido.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ingrese_porcentaje_valido.setWordWrap(True)
        self.label_ingrese_porcentaje_valido.setObjectName(
            "label_ingrese_porcentaje_valido"
        )

        self.retranslateUi(StockCregar)
        QtCore.QMetaObject.connectSlotsByName(StockCregar)

    def retranslateUi(self, StockCregar):
        _translate = QtCore.QCoreApplication.translate
        StockCregar.setWindowTitle(_translate("StockCregar", "Form"))
        self.label_15.setText(_translate("StockCregar", "LISTA DE PRODUCTOS"))
        self.boton_buscar_producto.setText(_translate("StockCregar", "Buscar"))
        self.boton_volver.setText(_translate("StockCregar", "Volver"))
        self.boton_agregar_producto.setText(
            _translate("StockCregar", "Agregar Producto")
        )
        self.boton_eliminar_producto.setText(
            _translate("StockCregar", "Eliminar Producto")
        )
        self.boton_modificar_producto.setText(
            _translate("StockCregar", "Modificar Producto")
        )
        self.boton_modificar_productos_gral.setText(
            _translate("StockCregar", "Modificar Productos Gral")
        )
        self.boton_cancelar_modificacion.setText(_translate("StockCregar", "Cancelar"))
        self.label_16.setText(_translate("StockCregar", "Producto:"))
        self.label_17.setText(_translate("StockCregar", "Stock"))
        self.label_18.setText(_translate("StockCregar", "Costo Inicial"))
        self.label_19.setText(_translate("StockCregar", "Descuento_1"))
        self.label_20.setText(_translate("StockCregar", "Descuento_2"))
        self.label_21.setText(_translate("StockCregar", "Aumento Efectivo"))
        self.label_22.setText(_translate("StockCregar", "Aumento MercadoLibre"))
        self.label_23.setText(_translate("StockCregar", "IVA"))
        self.label_24.setText(_translate("StockCregar", "Aumento Constructores"))
        self.boton_confirmar_registro.setText(_translate("StockCregar", "Confirmar"))
        self.label_25.setText(_translate("StockCregar", "$"))
        self.label_26.setText(_translate("StockCregar", "%"))
        self.label_27.setText(_translate("StockCregar", "%"))
        self.label_28.setText(_translate("StockCregar", "%"))
        self.label_29.setText(_translate("StockCregar", "%"))
        self.label_30.setText(_translate("StockCregar", "%"))
        self.label_31.setText(_translate("StockCregar", "%"))
        self.boton_confirmar_modificacion.setText(
            _translate("StockCregar", "Confirmar")
        )
        self.label_32.setText(_translate("StockCregar", "Que desea modificar?:"))
        self.boton_modificar_costo_inicial.setText(
            _translate("StockCregar", "Aumentar Costo Inicial")
        )
        self.boton_modificar_descuento_1.setText(
            _translate("StockCregar", "Nuevo descuento_1")
        )
        self.boton_modificar_descuento_2.setText(
            _translate("StockCregar", "Nuevo descuento_2")
        )
        self.boton_modificar_iva.setText(_translate("StockCregar", "Nuevo IVA"))
        self.boton_modificar_aumento_constructores.setText(
            _translate("StockCregar", "Nuevo aumento_constructores")
        )
        self.boton_modificar_aumento_efectivo.setText(
            _translate("StockCregar", "Nuevo aumento_efectivo")
        )
        self.boton_modificar_aumento_mercadolibre.setText(
            _translate("StockCregar", "Nuevo aumento_mercadolibre")
        )
        self.boton_cancelar_modificacion_gral.setText(
            _translate("StockCregar", "Cancelar")
        )
        self.label_ingrese_porcentaje.setText(
            _translate(
                "StockCregar",
                "Ingrese el nuevo porcentaje de aumento_constructores para todos los productos:",
            )
        )
        self.label_35.setText(_translate("StockCregar", "%"))
        self.boton_confirmar_modificacion_gral.setText(
            _translate("StockCregar", "Confirmar")
        )
