# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stock_disponible.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from ventanas.imagenes import imagenes


class Ui_StockDisponible(object):
    def setupUi(self, StockDisponible):
        StockDisponible.setObjectName("StockDisponible")
        StockDisponible.resize(1195, 877)
        StockDisponible.setMinimumSize(QtCore.QSize(1195, 877))
        StockDisponible.setMaximumSize(QtCore.QSize(1195, 877))
        StockDisponible.setStyleSheet("")
        self.widget = QtWidgets.QWidget(StockDisponible)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1195, 877))
        self.widget.setMinimumSize(QtCore.QSize(1195, 877))
        self.widget.setMaximumSize(QtCore.QSize(1195, 877))
        self.widget.setStyleSheet(
            "QPushButton{\n"
            "border:2px solid rgb(28, 165, 206);\n"
            "border-radius: 10px;\n"
            "color: #fff;\n"
            'font: 57 12pt "Yu Gothic Medium";\n'
            "padding:5px;\n"
            "background-color:none;\n"
            "}\n"
            "QPushButton:hover {\n"
            "color: rgb(28, 165, 206);\n"
            "border:1px solid #fff;\n"
            "}\n"
            "QPushButton:pressed {\n"
            "    padding-top: 10px;\n"
            "    padding-left: 10px;\n"
            "}\n"
            "\n"
            "QLineEdit{\n"
            "background-color:transparent;\n"
            "border-bottom:2px solid rgb(28, 165, 206);\n"
            "border-radius: 0px;\n"
            "padding: 7px;\n"
            "color: #fff;\n"
            "}\n"
            "QLineEdit:hover {\n"
            "background-color:transparent;\n"
            "}\n"
            "QLineEdit:focus {\n"
            "background-color:transparent;\n"
            "}\n"
            "QWidget#widget{\n"
            "background-image: url(:/stock_disponible/modern-2560-x-1600-background-od87qg1wfx087jbt.jpg);\n"
            "}\n"
            "QTreeView{\n"
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 190, 255, 113));\n"
            "color: #fff;\n"
            "border: 1px solid #000;\n"
            "}\n"
            "QHeaderView::section {\n"
            "color: #000;\n"
            "border: 1px solid #000;\n"
            "}\n"
            "QTreeView::item {\n"
            "color: #fff;\n"
            "}\n"
            ""
        )
        self.widget.setObjectName("widget")
        self.input_precio_unitario = QtWidgets.QLineEdit(self.widget)
        self.input_precio_unitario.setGeometry(QtCore.QRect(920, 510, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.input_precio_unitario.setFont(font)
        self.input_precio_unitario.setStyleSheet("")
        self.input_precio_unitario.setAlignment(QtCore.Qt.AlignCenter)
        self.input_precio_unitario.setObjectName("input_precio_unitario")
        self.label_eliminar_producto = QtWidgets.QLabel(self.widget)
        self.label_eliminar_producto.setGeometry(QtCore.QRect(560, 440, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_eliminar_producto.setFont(font)
        self.label_eliminar_producto.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_eliminar_producto.setStyleSheet(
            'font: 57 12pt "Yu Gothic Medium";\n' "color: #f00;\n" "background: none;"
        )
        self.label_eliminar_producto.setText("")
        self.label_eliminar_producto.setAlignment(QtCore.Qt.AlignCenter)
        self.label_eliminar_producto.setObjectName("label_eliminar_producto")
        self.label_ingresar_porcentaje = QtWidgets.QLabel(self.widget)
        self.label_ingresar_porcentaje.setGeometry(QtCore.QRect(840, 410, 281, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_ingresar_porcentaje.setFont(font)
        self.label_ingresar_porcentaje.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_ingresar_porcentaje.setStyleSheet(
            'font: 12pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_ingresar_porcentaje.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ingresar_porcentaje.setWordWrap(True)
        self.label_ingresar_porcentaje.setObjectName("label_ingresar_porcentaje")
        self.boton_confirmar_modificacion = QtWidgets.QPushButton(self.widget)
        self.boton_confirmar_modificacion.setGeometry(QtCore.QRect(930, 590, 121, 41))
        self.boton_confirmar_modificacion.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_confirmar_modificacion.setStyleSheet("")
        self.boton_confirmar_modificacion.setObjectName("boton_confirmar_modificacion")
        self.boton_confirmar_porcentaje = QtWidgets.QPushButton(self.widget)
        self.boton_confirmar_porcentaje.setGeometry(QtCore.QRect(930, 530, 101, 31))
        self.boton_confirmar_porcentaje.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_confirmar_porcentaje.setStyleSheet("")
        self.boton_confirmar_porcentaje.setObjectName("boton_confirmar_porcentaje")
        self.treeview_productos = QtWidgets.QTreeView(self.widget)
        self.treeview_productos.setGeometry(QtCore.QRect(20, 150, 541, 701))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.treeview_productos.setFont(font)
        self.treeview_productos.setStyleSheet("")
        self.treeview_productos.setObjectName("treeview_productos")
        self.label_precio_unitario = QtWidgets.QLabel(self.widget)
        self.label_precio_unitario.setGeometry(QtCore.QRect(870, 470, 241, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_precio_unitario.setFont(font)
        self.label_precio_unitario.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_precio_unitario.setStyleSheet(
            'font: 12pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_precio_unitario.setAlignment(QtCore.Qt.AlignCenter)
        self.label_precio_unitario.setObjectName("label_precio_unitario")
        self.boton_buscar_producto = QtWidgets.QPushButton(self.widget)
        self.boton_buscar_producto.setGeometry(QtCore.QRect(400, 90, 101, 31))
        self.boton_buscar_producto.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_buscar_producto.setStyleSheet("")
        self.boton_buscar_producto.setObjectName("boton_buscar_producto")
        self.boton_confirmar_registro = QtWidgets.QPushButton(self.widget)
        self.boton_confirmar_registro.setGeometry(QtCore.QRect(930, 590, 121, 41))
        self.boton_confirmar_registro.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_confirmar_registro.setStyleSheet("")
        self.boton_confirmar_registro.setObjectName("boton_confirmar_registro")
        self.label_stock = QtWidgets.QLabel(self.widget)
        self.label_stock.setGeometry(QtCore.QRect(870, 400, 241, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_stock.setFont(font)
        self.label_stock.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_stock.setStyleSheet(
            'font: 12pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_stock.setAlignment(QtCore.Qt.AlignCenter)
        self.label_stock.setObjectName("label_stock")
        self.label_signo_peso = QtWidgets.QLabel(self.widget)
        self.label_signo_peso.setGeometry(QtCore.QRect(900, 510, 21, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_signo_peso.setFont(font)
        self.label_signo_peso.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_signo_peso.setStyleSheet(
            'font: 15pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_signo_peso.setAlignment(QtCore.Qt.AlignCenter)
        self.label_signo_peso.setWordWrap(True)
        self.label_signo_peso.setObjectName("label_signo_peso")
        self.input_nombre_producto = QtWidgets.QLineEdit(self.widget)
        self.input_nombre_producto.setGeometry(QtCore.QRect(860, 360, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.input_nombre_producto.setFont(font)
        self.input_nombre_producto.setStyleSheet("")
        self.input_nombre_producto.setAlignment(QtCore.Qt.AlignCenter)
        self.input_nombre_producto.setObjectName("input_nombre_producto")
        self.input_stock = QtWidgets.QLineEdit(self.widget)
        self.input_stock.setGeometry(QtCore.QRect(920, 430, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.input_stock.setFont(font)
        self.input_stock.setStyleSheet("")
        self.input_stock.setAlignment(QtCore.Qt.AlignCenter)
        self.input_stock.setObjectName("input_stock")
        self.label_porcentaje = QtWidgets.QLabel(self.widget)
        self.label_porcentaje.setGeometry(QtCore.QRect(1020, 480, 31, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_porcentaje.setFont(font)
        self.label_porcentaje.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_porcentaje.setStyleSheet(
            'font: 15pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_porcentaje.setAlignment(QtCore.Qt.AlignCenter)
        self.label_porcentaje.setWordWrap(True)
        self.label_porcentaje.setObjectName("label_porcentaje")
        self.label_error = QtWidgets.QLabel(self.widget)
        self.label_error.setGeometry(QtCore.QRect(870, 550, 241, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_error.setFont(font)
        self.label_error.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_error.setStyleSheet(
            'font: 12pt "MS Shell Dlg 2";\n' "color: #f00;\n" "background: none;"
        )
        self.label_error.setText("")
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setWordWrap(True)
        self.label_error.setObjectName("label_error")
        self.boton_volver = QtWidgets.QPushButton(self.widget)
        self.boton_volver.setGeometry(QtCore.QRect(1080, 20, 91, 31))
        self.boton_volver.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_volver.setStyleSheet("")
        self.boton_volver.setObjectName("boton_volver")
        self.boton_modificar_producto = QtWidgets.QPushButton(self.widget)
        self.boton_modificar_producto.setGeometry(QtCore.QRect(570, 510, 231, 51))
        self.boton_modificar_producto.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_modificar_producto.setStyleSheet("")
        self.boton_modificar_producto.setObjectName("boton_modificar_producto")
        self.boton_modificar_precio_general = QtWidgets.QPushButton(self.widget)
        self.boton_modificar_precio_general.setGeometry(QtCore.QRect(570, 630, 231, 51))
        self.boton_modificar_precio_general.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_modificar_precio_general.setStyleSheet("")
        self.boton_modificar_precio_general.setObjectName(
            "boton_modificar_precio_general"
        )
        self.label_modificar_producto = QtWidgets.QLabel(self.widget)
        self.label_modificar_producto.setGeometry(QtCore.QRect(560, 560, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_modificar_producto.setFont(font)
        self.label_modificar_producto.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_modificar_producto.setStyleSheet(
            'font: 57 12pt "Yu Gothic Medium";\n' "color: #f00;\n" "background: none;"
        )
        self.label_modificar_producto.setText("")
        self.label_modificar_producto.setAlignment(QtCore.Qt.AlignCenter)
        self.label_modificar_producto.setObjectName("label_modificar_producto")
        self.input_porcentaje = QtWidgets.QLineEdit(self.widget)
        self.input_porcentaje.setGeometry(QtCore.QRect(950, 470, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.input_porcentaje.setFont(font)
        self.input_porcentaje.setStyleSheet("")
        self.input_porcentaje.setAlignment(QtCore.Qt.AlignCenter)
        self.input_porcentaje.setObjectName("input_porcentaje")
        self.boton_agregar_producto = QtWidgets.QPushButton(self.widget)
        self.boton_agregar_producto.setGeometry(QtCore.QRect(570, 280, 231, 51))
        self.boton_agregar_producto.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_agregar_producto.setStyleSheet("")
        self.boton_agregar_producto.setObjectName("boton_agregar_producto")
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setGeometry(QtCore.QRect(100, 40, 341, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setStyleSheet(
            'font: 25pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.producto_no_encontrado = QtWidgets.QLabel(self.widget)
        self.producto_no_encontrado.setGeometry(QtCore.QRect(140, 120, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.producto_no_encontrado.setFont(font)
        self.producto_no_encontrado.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.producto_no_encontrado.setStyleSheet(
            'font: 57 12pt "Yu Gothic Medium";\n' "color: #f00;\n" "background: none;"
        )
        self.producto_no_encontrado.setText("")
        self.producto_no_encontrado.setAlignment(QtCore.Qt.AlignCenter)
        self.producto_no_encontrado.setObjectName("producto_no_encontrado")
        self.boton_eliminar_producto = QtWidgets.QPushButton(self.widget)
        self.boton_eliminar_producto.setGeometry(QtCore.QRect(570, 390, 231, 51))
        self.boton_eliminar_producto.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_eliminar_producto.setStyleSheet("")
        self.boton_eliminar_producto.setObjectName("boton_eliminar_producto")
        self.label_ingresar_porcentaje_error = QtWidgets.QLabel(self.widget)
        self.label_ingresar_porcentaje_error.setGeometry(
            QtCore.QRect(860, 500, 261, 21)
        )
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_ingresar_porcentaje_error.setFont(font)
        self.label_ingresar_porcentaje_error.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_ingresar_porcentaje_error.setStyleSheet(
            'font: 12pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_ingresar_porcentaje_error.setText("")
        self.label_ingresar_porcentaje_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ingresar_porcentaje_error.setWordWrap(True)
        self.label_ingresar_porcentaje_error.setObjectName(
            "label_ingresar_porcentaje_error"
        )
        self.input_buscar_producto = QtWidgets.QLineEdit(self.widget)
        self.input_buscar_producto.setGeometry(QtCore.QRect(80, 90, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.input_buscar_producto.setFont(font)
        self.input_buscar_producto.setStyleSheet("")
        self.input_buscar_producto.setAlignment(QtCore.Qt.AlignCenter)
        self.input_buscar_producto.setObjectName("input_buscar_producto")
        self.label_nombre_producto = QtWidgets.QLabel(self.widget)
        self.label_nombre_producto.setGeometry(QtCore.QRect(870, 320, 241, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_nombre_producto.setFont(font)
        self.label_nombre_producto.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_nombre_producto.setStyleSheet(
            'font: 12pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_nombre_producto.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nombre_producto.setObjectName("label_nombre_producto")

        self.retranslateUi(StockDisponible)
        QtCore.QMetaObject.connectSlotsByName(StockDisponible)

    def retranslateUi(self, StockDisponible):
        _translate = QtCore.QCoreApplication.translate
        StockDisponible.setWindowTitle(_translate("StockDisponible", "Form"))
        self.label_ingresar_porcentaje.setText(
            _translate(
                "StockDisponible",
                "Ingrese el porcentaje de aumento/disminucion del precio unitario general:",
            )
        )
        self.boton_confirmar_modificacion.setText(
            _translate("StockDisponible", "Confirmar")
        )
        self.boton_confirmar_porcentaje.setText(
            _translate("StockDisponible", "Confirmar")
        )
        self.label_precio_unitario.setText(
            _translate("StockDisponible", "Precio unitaro:")
        )
        self.boton_buscar_producto.setText(_translate("StockDisponible", "Buscar"))
        self.boton_confirmar_registro.setText(
            _translate("StockDisponible", "Confirmar")
        )
        self.label_stock.setText(_translate("StockDisponible", "Stock inicial:"))
        self.label_signo_peso.setText(_translate("StockDisponible", "$"))
        self.label_porcentaje.setText(_translate("StockDisponible", "%"))
        self.boton_volver.setText(_translate("StockDisponible", "Volver"))
        self.boton_modificar_producto.setText(
            _translate("StockDisponible", "Modificar Producto")
        )
        self.boton_modificar_precio_general.setText(
            _translate("StockDisponible", "Modificar Precio General")
        )
        self.boton_agregar_producto.setText(
            _translate("StockDisponible", "Agregar Producto")
        )
        self.label_15.setText(_translate("StockDisponible", "LISTA DE PRODUCTOS"))
        self.boton_eliminar_producto.setText(
            _translate("StockDisponible", "Eliminar Producto")
        )
        self.label_nombre_producto.setText(
            _translate("StockDisponible", "Nombre del nuevo producto:")
        )
