# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'usuarios.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ventanas.imagenes import imagenes


class Ui_Usuarios(object):
    def setupUi(self, Usuarios):
        Usuarios.setObjectName("Usuarios")
        Usuarios.resize(1195, 722)
        Usuarios.setMinimumSize(QtCore.QSize(1195, 645))
        Usuarios.setMaximumSize(QtCore.QSize(1195, 645))
        Usuarios.setStyleSheet("")
        self.widget = QtWidgets.QWidget(Usuarios)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1195, 645))
        self.widget.setMinimumSize(QtCore.QSize(1195, 645))
        self.widget.setMaximumSize(QtCore.QSize(1195, 645))
        self.widget.setStyleSheet(
            "\n"
            "QTreeView{\n"
            "color: #fff;\n"
            "border: 1px solid #000;\n"
            "    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(163, 163, 163, 113));\n"
            "}\n"
            "QHeaderView::section {\n"
            "color: #000;\n"
            "border: 1px solid #000;\n"
            "font-size: 15px;\n"
            "}\n"
            "QTreeView::item {\n"
            "color: #fff;\n"
            "}\n"
            "QPushButton{\n"
            "border: 1px solid  #fff;\n"
            "border-radius:15px;\n"
            "color: #fff;\n"
            'font: 57 14pt "Yu Gothic Medium";\n'
            "padding:5px;\n"
            "}\n"
            "QPushButton:hover {\n"
            "border: 1px solid   rgb(25, 166, 0);\n"
            "}\n"
            "QPushButton:pressed {\n"
            "border: 1px solid   rgb(25, 166, 0);\n"
            "padding-top: 10px;\n"
            "padding-left: 10px;\n"
            "}\n"
            "\n"
            "QLineEdit{\n"
            "border: 1px solid  #fff;\n"
            "    background-color: #000;\n"
            "border-radius: 10px;\n"
            "padding: 7px;\n"
            "color: #fff;\n"
            'font: 11pt "MS Shell Dlg 2";\n'
            "}\n"
            "QLineEdit:hover {\n"
            "border: 1px solid   rgb(25, 166, 0);\n"
            "}\n"
            "QLineEdit:focus {\n"
            "border: 1px solid   rgb(25, 166, 0);\n"
            "}\n"
            "QLabel{\n"
            'font: 12pt "MS Shell Dlg 2";\n'
            "color: #fff;\n"
            "background: none;\n"
            "}\n"
            "QWidget#widget{\n"
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.494318 rgba(0, 0, 0, 241), stop:1 rgba(255, 255, 255, 255));\n"
            "    background-image: url(:/usuarios/black-dark-cubes-abstract.jpg);\n"
            "}"
        )
        self.widget.setObjectName("widget")
        self.label_vendedor_no_seleccionado = QtWidgets.QLabel(self.widget)
        self.label_vendedor_no_seleccionado.setGeometry(QtCore.QRect(70, 200, 361, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_vendedor_no_seleccionado.setFont(font)
        self.label_vendedor_no_seleccionado.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_vendedor_no_seleccionado.setStyleSheet("color: #f00;")
        self.label_vendedor_no_seleccionado.setText("")
        self.label_vendedor_no_seleccionado.setAlignment(QtCore.Qt.AlignCenter)
        self.label_vendedor_no_seleccionado.setObjectName(
            "label_vendedor_no_seleccionado"
        )
        self.label_vendedor_no_seleccionado_2 = QtWidgets.QLabel(self.widget)
        self.label_vendedor_no_seleccionado_2.setGeometry(
            QtCore.QRect(780, 200, 361, 31)
        )
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_vendedor_no_seleccionado_2.setFont(font)
        self.label_vendedor_no_seleccionado_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_vendedor_no_seleccionado_2.setStyleSheet("color: #f00;")
        self.label_vendedor_no_seleccionado_2.setText("")
        self.label_vendedor_no_seleccionado_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_vendedor_no_seleccionado_2.setObjectName(
            "label_vendedor_no_seleccionado_2"
        )
        self.label_ingresar_usuario = QtWidgets.QLabel(self.widget)
        self.label_ingresar_usuario.setGeometry(QtCore.QRect(430, 330, 371, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_ingresar_usuario.setFont(font)
        self.label_ingresar_usuario.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_ingresar_usuario.setStyleSheet("")
        self.label_ingresar_usuario.setText("")
        self.label_ingresar_usuario.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ingresar_usuario.setObjectName("label_ingresar_usuario")
        self.nuevo_usuario = QtWidgets.QLineEdit(self.widget)
        self.nuevo_usuario.setGeometry(QtCore.QRect(470, 370, 281, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nuevo_usuario.setFont(font)
        self.nuevo_usuario.setStyleSheet(
            "border-radius: 10px;\n" "padding: 7px;\n" "color: #fff;"
        )
        self.nuevo_usuario.setObjectName("nuevo_usuario")
        self.boton_registrar_usuario_autorizado = QtWidgets.QPushButton(self.widget)
        self.boton_registrar_usuario_autorizado.setGeometry(
            QtCore.QRect(820, 90, 291, 51)
        )
        self.boton_registrar_usuario_autorizado.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_registrar_usuario_autorizado.setStyleSheet("")
        self.boton_registrar_usuario_autorizado.setObjectName(
            "boton_registrar_usuario_autorizado"
        )
        self.producto_no_encontrado = QtWidgets.QLabel(self.widget)
        self.producto_no_encontrado.setGeometry(QtCore.QRect(860, 240, 231, 31))
        self.producto_no_encontrado.setStyleSheet(
            'font: 16pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.producto_no_encontrado.setText("")
        self.producto_no_encontrado.setObjectName("producto_no_encontrado")
        self.label_ingresar_contrasenia = QtWidgets.QLabel(self.widget)
        self.label_ingresar_contrasenia.setGeometry(QtCore.QRect(420, 410, 381, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_ingresar_contrasenia.setFont(font)
        self.label_ingresar_contrasenia.setStyleSheet("")
        self.label_ingresar_contrasenia.setText("")
        self.label_ingresar_contrasenia.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ingresar_contrasenia.setObjectName("label_ingresar_contrasenia")
        self.nueva_contrasenia = QtWidgets.QLineEdit(self.widget)
        self.nueva_contrasenia.setGeometry(QtCore.QRect(470, 450, 281, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nueva_contrasenia.setFont(font)
        self.nueva_contrasenia.setStyleSheet(
            "border-radius: 10px;\n" "padding: 7px;\n" "color: #fff;"
        )
        self.nueva_contrasenia.setObjectName("nueva_contrasenia")
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setGeometry(QtCore.QRect(150, 40, 211, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setStyleSheet(
            'font: 20pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.boton_registrar_vendedor = QtWidgets.QPushButton(self.widget)
        self.boton_registrar_vendedor.setGeometry(QtCore.QRect(110, 90, 291, 51))
        self.boton_registrar_vendedor.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_registrar_vendedor.setStyleSheet("")
        self.boton_registrar_vendedor.setObjectName("boton_registrar_vendedor")
        self.treeview_vendedores = QtWidgets.QTreeView(self.widget)
        self.treeview_vendedores.setGeometry(QtCore.QRect(100, 230, 311, 411))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.treeview_vendedores.setFont(font)
        self.treeview_vendedores.setStyleSheet("")
        self.treeview_vendedores.setObjectName("treeview_vendedores")
        self.modelo_vendedores = QtGui.QStandardItemModel()
        self.treeview_vendedores.setModel(self.modelo_vendedores)
        self.modelo_vendedores.setHorizontalHeaderLabels(
            [
                "Usuario",
                "Contraseña",
            ]
        )
        header = self.treeview_vendedores.header()
        header.setDefaultAlignment(QtCore.Qt.AlignHCenter)
        header.resizeSection(0, 155)
        header.resizeSection(1, 50)

        self.boton_eliminar_vendedor = QtWidgets.QPushButton(self.widget)
        self.boton_eliminar_vendedor.setGeometry(QtCore.QRect(110, 150, 291, 51))
        self.boton_eliminar_vendedor.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_eliminar_vendedor.setStyleSheet("")
        self.boton_eliminar_vendedor.setObjectName("boton_eliminar_vendedor")
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setGeometry(QtCore.QRect(760, 40, 401, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setStyleSheet(
            'font: 20pt "MS Shell Dlg 2";\n' "color: #fff;\n" "background: none;"
        )
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.treeview_usuarios_autorizados = QtWidgets.QTreeView(self.widget)
        self.treeview_usuarios_autorizados.setGeometry(QtCore.QRect(810, 230, 311, 411))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.treeview_usuarios_autorizados.setFont(font)
        self.treeview_usuarios_autorizados.setStyleSheet("")
        self.treeview_usuarios_autorizados.setAnimated(False)
        self.treeview_usuarios_autorizados.setObjectName(
            "treeview_usuarios_autorizados"
        )
        self.modelo_usuarios_autorizados = QtGui.QStandardItemModel()
        self.treeview_usuarios_autorizados.setModel(self.modelo_usuarios_autorizados)
        self.modelo_usuarios_autorizados.setHorizontalHeaderLabels(
            [
                "Usuario",
                "Contraseña",
            ]
        )
        header = self.treeview_usuarios_autorizados.header()
        header.setDefaultAlignment(QtCore.Qt.AlignHCenter)
        header.resizeSection(0, 155)
        header.resizeSection(1, 50)

        self.treeview_usuarios_autorizados.header().setSortIndicatorShown(False)
        self.boton_eliminar_usuario_autorizado = QtWidgets.QPushButton(self.widget)
        self.boton_eliminar_usuario_autorizado.setGeometry(
            QtCore.QRect(820, 150, 291, 51)
        )
        self.boton_eliminar_usuario_autorizado.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_eliminar_usuario_autorizado.setStyleSheet("")
        self.boton_eliminar_usuario_autorizado.setObjectName(
            "boton_eliminar_usuario_autorizado"
        )
        self.boton_confirmar_registro = QtWidgets.QPushButton(self.widget)
        self.boton_confirmar_registro.setGeometry(QtCore.QRect(550, 510, 131, 41))
        self.boton_confirmar_registro.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.boton_confirmar_registro.setStyleSheet("")
        self.boton_confirmar_registro.setObjectName("boton_confirmar_registro")
        self.boton_volver = QtWidgets.QPushButton(self.widget)
        self.boton_volver.setGeometry(QtCore.QRect(570, 610, 91, 31))
        self.boton_volver.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_volver.setStyleSheet("\n" 'font: 57 11pt "Yu Gothic Medium";')
        self.boton_volver.setObjectName("boton_volver")

        self.retranslateUi(Usuarios)
        QtCore.QMetaObject.connectSlotsByName(Usuarios)

    def retranslateUi(self, Usuarios):
        _translate = QtCore.QCoreApplication.translate
        Usuarios.setWindowTitle(_translate("Usuarios", "Form"))
        self.boton_registrar_usuario_autorizado.setText(
            _translate("Usuarios", "Registrar Usuario Autorizado")
        )
        self.label_15.setText(_translate("Usuarios", "VENDEDORES"))
        self.boton_registrar_vendedor.setText(
            _translate("Usuarios", "Registrar Vendedor")
        )
        self.boton_eliminar_vendedor.setText(
            _translate("Usuarios", "Eliminar Vendedor")
        )
        self.label_16.setText(_translate("Usuarios", "USUARIOS AUTORIZADOS"))
        self.boton_eliminar_usuario_autorizado.setText(
            _translate("Usuarios", "Eliminar Usuario Autorizado")
        )
        self.boton_confirmar_registro.setText(_translate("Usuarios", "Confrmar"))
        self.boton_volver.setText(_translate("Usuarios", "Volver"))
